/* Generated by json-schema-generate. Do not modify. */

#include <stddef.h>

static const struct { const char *json; size_t size; unsigned int is_valid; } clipboard_fuzz[] = {
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 148, 0 },  /* 0 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":[null],\"type\":[null]}", 60, 0 },  /* 1 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 103, 0 },  /* 2 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":[null,null]}", 49, 0 },  /* 3 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null,\"0\":null}", 54, 0 },  /* 4 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"0\":null}", 42, 0 },  /* 5 */
	{ "{\"id\":\"\",\"type\":\"\"}", 19, 0 },  /* 6 */
	{ "{\"body\":{\"content\":[]},\"id\":[null],\"0\":null}", 44, 0 },  /* 7 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null}", 116, 1 },  /* 8 */
	{ "{\"body\":{\"content\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 92, 0 },  /* 9 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null}", 90, 0 },  /* 10 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 79, 0 },  /* 11 */
	{ "{\"body\":null,\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 75, 0 },  /* 12 */
	{ "{\"id\":[null],\"type\":[null]}", 27, 0 },  /* 13 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"type\":\"kdeconnect.connect\",\"0\":null}", 68, 0 },  /* 14 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 117, 0 },  /* 15 */
	{ "{\"body\":{\"content\":[]},\"id\":[null],\"type\":[null]}", 49, 0 },  /* 16 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 90, 0 },  /* 17 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"type\":[null]}", 48, 0 },  /* 18 */
	{ "{\"id\":[],\"type\":[]}", 19, 0 },  /* 19 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 98, 0 },  /* 20 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 91, 0 },  /* 21 */
	{ "{\"body\":{\"content\":\"test content\"},\"type\":\"kdeconnect.connect\"}", 63, 0 },  /* 22 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\",\"0\":null}", 121, 0 },  /* 23 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 164, 0 },  /* 24 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 94, 0 },  /* 25 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 91, 0 },  /* 26 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 116, 0 },  /* 27 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{\"0\":null},\"0\":null}", 108, 0 },  /* 28 */
	{ "{\"body\":{\"content\":{}},\"id\":null}", 33, 0 },  /* 29 */
	{ "{\"body\":[null],\"type\":null}", 27, 0 },  /* 30 */
	{ "{\"body\":{\"content\":\"\"},\"id\":1,\"0\":null}", 39, 0 },  /* 31 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 106, 0 },  /* 32 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 107, 1 },  /* 33 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 109, 0 },  /* 34 */
	{ "{\"body\":{\"content\":[]},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 89, 0 },  /* 35 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null}", 88, 1 },  /* 36 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 85, 0 },  /* 37 */
	{ "{\"body\":[null],\"id\":null,\"type\":null}", 37, 0 },  /* 38 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{},\"0\":null}", 53, 0 },  /* 39 */
	{ "{\"body\":{\"content\":{}},\"type\":null}", 35, 0 },  /* 40 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"id\":{}}", 80, 0 },  /* 41 */
	{ "{\"body\":{\"content\":\"\"},\"id\":1,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 98, 1 },  /* 42 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":{\"0\":null}}", 89, 0 },  /* 43 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 128, 1 },  /* 44 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 75, 0 },  /* 45 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 76, 0 },  /* 46 */
	{ "{\"body\":{\"content\":[null]},\"type\":[null,null],\"0\":null}", 55, 0 },  /* 47 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"0\":null}", 96, 0 },  /* 48 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\"}", 112, 0 },  /* 49 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null}", 45, 0 },  /* 50 */
	{ "{\"body\":[null],\"id\":null}", 25, 0 },  /* 51 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":{\"0\":null},\"0\":null}", 98, 0 },  /* 52 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":0}", 42, 0 },  /* 53 */
	{ "{\"body\":{\"content\":[null,null]},\"type\":[null,null],\"0\":null}", 60, 0 },  /* 54 */
	{ "{\"body\":{\"content\":[]},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 98, 0 },  /* 55 */
	{ "{\"body\":null,\"id\":null,\"type\":null,\"0\":null}", 44, 0 },  /* 56 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{},\"type\":{},\"0\":null}", 63, 0 },  /* 57 */
	{ "{\"body\":{},\"id\":[null],\"0\":null}", 32, 0 },  /* 58 */
	{ "{\"body\":{},\"id\":[null],\"type\":[null],\"0\":null}", 46, 0 },  /* 59 */
	{ "{\"body\":[null,null],\"id\":{},\"0\":null}", 37, 0 },  /* 60 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null}", 82, 0 },  /* 61 */
	{ "{\"body\":null,\"id\":null}", 23, 0 },  /* 62 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.connect\"}", 67, 1 },  /* 63 */
	{ "[]", 2, 0 },  /* 64 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 165, 0 },  /* 65 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 143, 0 },  /* 66 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\"}", 98, 1 },  /* 67 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"type\":{}}", 82, 0 },  /* 68 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[]}", 86, 0 },  /* 69 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 150, 1 },  /* 70 */
	{ "{\"id\":[null],\"type\":[null],\"0\":null}", 36, 0 },  /* 71 */
	{ "{\"body\":{\"content\":\"test content\"},\"type\":\"kdeconnect.connect\",\"0\":null}", 72, 0 },  /* 72 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null}", 128, 1 },  /* 73 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 84, 0 },  /* 74 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null],\"0\":null}", 62, 0 },  /* 75 */
	{ "{\"body\":\"\",\"type\":\"\",\"0\":null}", 30, 0 },  /* 76 */
	{ "{\"id\":{},\"type\":{},\"0\":null}", 28, 0 },  /* 77 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 119, 1 },  /* 78 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[]}", 94, 0 },  /* 79 */
	{ "{\"body\":{\"content\":[null]},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 112, 0 },  /* 80 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 93, 0 },  /* 81 */
	{ "{\"id\":1,\"type\":\"kdeconnect.connect\"}", 36, 0 },  /* 82 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 99, 0 },  /* 83 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 107, 0 },  /* 84 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 77, 0 },  /* 85 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 88, 0 },  /* 86 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"type\":{},\"0\":null}", 55, 0 },  /* 87 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"type\":\"kdeconnect.connect\",\"0\":null}", 81, 0 },  /* 88 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{}}", 80, 0 },  /* 89 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 145, 0 },  /* 90 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 169, 0 },  /* 91 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 150, 0 },  /* 92 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\"}", 91, 0 },  /* 93 */
	{ "{\"body\":{},\"type\":[null]}", 25, 0 },  /* 94 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":[],\"type\":[],\"0\":null}", 67, 0 },  /* 95 */
	{ "{\"body\":{\"content\":[null]},\"id\":[null,null],\"0\":null}", 53, 0 },  /* 96 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 106, 0 },  /* 97 */
	{ "{\"body\":{\"content\":\"\"},\"id\":1}", 30, 0 },  /* 98 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 94, 0 },  /* 99 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 82, 0 },  /* 100 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 115, 0 },  /* 101 */
	{ "{\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 44, 0 },  /* 102 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"type\":null}", 79, 0 },  /* 103 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 138, 0 },  /* 104 */
	{ "{\"body\":{\"content\":[null,null]},\"type\":[null,null]}", 51, 0 },  /* 105 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 80, 0 },  /* 106 */
	{ "{\"body\":{\"content\":[]},\"id\":[null],\"type\":[null],\"0\":null}", 58, 0 },  /* 107 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":[],\"type\":[],\"0\":null}", 59, 0 },  /* 108 */
	{ "\"\"", 2, 0 },  /* 109 */
	{ "{\"body\":{\"content\":null},\"type\":\"\"}", 35, 0 },  /* 110 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\",\"0\":null}", 112, 0 },  /* 111 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.connect\"}", 79, 1 },  /* 112 */
	{ "{\"body\":{},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 86, 0 },  /* 113 */
	{ "{\"body\":null,\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 84, 0 },  /* 114 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"type\":{\"0\":null},\"0\":null}", 59, 0 },  /* 115 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":[null,null],\"0\":null}", 58, 0 },  /* 116 */
	{ "{\"body\":[null,null],\"type\":{}}", 30, 0 },  /* 117 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null}}", 87, 0 },  /* 118 */
	{ "{\"id\":{\"0\":null},\"type\":{\"0\":null}}", 35, 0 },  /* 119 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null}", 75, 0 },  /* 120 */
	{ "{\"body\":{\"content\":[]},\"type\":[null]}", 37, 0 },  /* 121 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"type\":\"kdeconnect.connect\"}", 72, 0 },  /* 122 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 156, 0 },  /* 123 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[]}", 81, 0 },  /* 124 */
	{ "{\"body\":{},\"type\":[null],\"0\":null}", 34, 0 },  /* 125 */
	{ "{\"body\":[],\"id\":\"\",\"0\":null}", 28, 0 },  /* 126 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 139, 0 },  /* 127 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{\"0\":null}}", 99, 0 },  /* 128 */
	{ "{\"body\":{\"content\":[]},\"type\":[null],\"0\":null}", 46, 0 },  /* 129 */
	{ "{\"body\":null,\"id\":null,\"0\":null}", 32, 0 },  /* 130 */
	{ "{\"body\":\"\",\"id\":\"\",\"0\":null}", 28, 0 },  /* 131 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0}", 79, 0 },  /* 132 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 69, 0 },  /* 133 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 117, 0 },  /* 134 */
	{ "{\"body\":[null,null],\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 78, 0 },  /* 135 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"type\":[null],\"0\":null}", 57, 0 },  /* 136 */
	{ "{\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null}", 45, 0 },  /* 137 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\",\"0\":null}", 38, 0 },  /* 138 */
	{ "{\"body\":{\"content\":{}},\"type\":null,\"0\":null}", 44, 0 },  /* 139 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"type\":[],\"0\":null}", 51, 0 },  /* 140 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 80, 0 },  /* 141 */
	{ "{\"id\":null,\"type\":null,\"0\":null}", 32, 0 },  /* 142 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\"}", 29, 0 },  /* 143 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 107, 0 },  /* 144 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 130, 0 },  /* 145 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\"}", 100, 0 },  /* 146 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 108, 0 },  /* 147 */
	{ "{\"body\":{},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 77, 0 },  /* 148 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null}", 79, 1 },  /* 149 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":1}", 38, 0 },  /* 150 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 103, 0 },  /* 151 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"type\":[null,null]}", 50, 0 },  /* 152 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"type\":[null,null],\"0\":null}", 59, 0 },  /* 153 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 89, 0 },  /* 154 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[]}", 92, 0 },  /* 155 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 147, 1 },  /* 156 */
	{ "{\"id\":0,\"type\":[],\"0\":null}", 27, 0 },  /* 157 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 157, 0 },  /* 158 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 91, 0 },  /* 159 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.connect\",\"0\":null}", 129, 0 },  /* 160 */
	{ "{\"body\":{\"content\":[null]},\"type\":[null,null]}", 46, 0 },  /* 161 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 100, 0 },  /* 162 */
	{ "{\"body\":{\"content\":[null]},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 72, 0 },  /* 163 */
	{ "{\"body\":{\"0\":null},\"id\":\"\"}", 27, 0 },  /* 164 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\"}", 107, 1 },  /* 165 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{}}", 44, 0 },  /* 166 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":0,\"type\":\"kdeconnect.connect\"}", 70, 1 },  /* 167 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[]}", 84, 0 },  /* 168 */
	{ "{\"body\":{\"content\":\"\"},\"id\":1,\"type\":\"kdeconnect.connect\"}", 58, 1 },  /* 169 */
	{ "{\"body\":\"\",\"id\":\"\",\"type\":\"\"}", 29, 0 },  /* 170 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 130, 0 },  /* 171 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\",\"0\":null}", 100, 0 },  /* 172 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null,null]}", 48, 0 },  /* 173 */
	{ "{\"body\":[null],\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 77, 0 },  /* 174 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":0,\"0\":null}", 51, 0 },  /* 175 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 90, 0 },  /* 176 */
	{ "{\"body\":[],\"type\":\"\"}", 21, 0 },  /* 177 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null}", 103, 0 },  /* 178 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\"}", 103, 0 },  /* 179 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":[null],\"type\":[null],\"0\":null}", 69, 0 },  /* 180 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"type\":[null]}", 55, 0 },  /* 181 */
	{ "{\"body\":{\"content\":\"\"},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 107, 1 },  /* 182 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 138, 1 },  /* 183 */
	{ "{\"id\":{},\"type\":{}}", 19, 0 },  /* 184 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 97, 0 },  /* 185 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 116, 0 },  /* 186 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":{\"0\":null},\"0\":null}", 57, 0 },  /* 187 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 156, 1 },  /* 188 */
	{ "{\"body\":{},\"id\":[null],\"type\":[null]}", 37, 0 },  /* 189 */
	{ "{\"id\":0,\"type\":\"kdeconnect.connect\"}", 36, 0 },  /* 190 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 116, 1 },  /* 191 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":[null],\"0\":null}", 55, 0 },  /* 192 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 101, 0 },  /* 193 */
	{ "{\"id\":0,\"type\":[]}", 18, 0 },  /* 194 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 95, 0 },  /* 195 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null}", 76, 1 },  /* 196 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null}}", 90, 0 },  /* 197 */
	{ "{\"body\":{\"content\":\"\"},\"type\":\"kdeconnect.connect\"}", 51, 0 },  /* 198 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":1,\"0\":null}", 48, 0 },  /* 199 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\"}", 110, 1 },  /* 200 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":null}", 84, 0 },  /* 201 */
	{ "{\"body\":{\"content\":null},\"id\":\"\"}", 33, 0 },  /* 202 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{\"0\":null},\"0\":null}", 101, 0 },  /* 203 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 94, 0 },  /* 204 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 115, 0 },  /* 205 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":[],\"0\":null}", 57, 0 },  /* 206 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":[]}", 40, 0 },  /* 207 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 121, 0 },  /* 208 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 66, 0 },  /* 209 */
	{ "{\"id\":\"\",\"type\":\"\",\"0\":null}", 28, 0 },  /* 210 */
	{ "{\"body\":{\"0\":null},\"type\":\"\"}", 29, 0 },  /* 211 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 99, 0 },  /* 212 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 159, 1 },  /* 213 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 134, 0 },  /* 214 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 89, 0 },  /* 215 */
	{ "{\"body\":[null,null],\"type\":{},\"0\":null}", 39, 0 },  /* 216 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 155, 0 },  /* 217 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null,null],\"0\":null}", 57, 0 },  /* 218 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[]}", 82, 0 },  /* 219 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 90, 0 },  /* 220 */
	{ "{\"id\":[],\"type\":[],\"0\":null}", 28, 0 },  /* 221 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 143, 0 },  /* 222 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 91, 0 },  /* 223 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 139, 0 },  /* 224 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"additionalProperties-test-unique\":null}", 129, 0 },  /* 225 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 91, 0 },  /* 226 */
	{ "{\"body\":\"\",\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 78, 0 },  /* 227 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":0,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 110, 1 },  /* 228 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null],\"type\":[null]}", 67, 0 },  /* 229 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"id\":0}", 70, 0 },  /* 230 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"0\":null}", 106, 0 },  /* 231 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null],\"type\":[null],\"0\":null}", 76, 0 },  /* 232 */
	{ "{\"body\":[null,null],\"id\":{},\"type\":{}}", 38, 0 },  /* 233 */
	{ "{\"body\":null,\"type\":null,\"0\":null}", 34, 0 },  /* 234 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"type\":\"kdeconnect.connect\"}", 59, 0 },  /* 235 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"type\":[]}", 42, 0 },  /* 236 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 237 */
	{ "{\"body\":{\"0\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 77, 0 },  /* 238 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"type\":{}}", 73, 0 },  /* 239 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[]}", 89, 0 },  /* 240 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":[],\"type\":[]}", 50, 0 },  /* 241 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"type\":{}}", 46, 0 },  /* 242 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 88, 0 },  /* 243 */
	{ "{\"body\":[],\"id\":\"\"}", 19, 0 },  /* 244 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 168, 1 },  /* 245 */
	{ "{\"body\":{\"0\":null},\"type\":\"\",\"0\":null}", 38, 0 },  /* 246 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 93, 0 },  /* 247 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":1,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 106, 0 },  /* 248 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 98, 0 },  /* 249 */
	{ "{\"body\":{\"content\":null},\"id\":\"\",\"type\":\"\"}", 43, 0 },  /* 250 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 121, 0 },  /* 251 */
	{ "{\"id\":[],\"type\":\"kdeconnect.connect\"}", 37, 0 },  /* 252 */
	{ "{\"body\":{\"content\":[]},\"id\":[null]}", 35, 0 },  /* 253 */
	{ "{\"body\":\"\",\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 69, 0 },  /* 254 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"type\":{\"0\":null}}", 50, 0 },  /* 255 */
	{ "{\"body\":{\"content\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 83, 0 },  /* 256 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 115, 0 },  /* 257 */
	{ "{\"body\":\"\",\"type\":\"\"}", 21, 0 },  /* 258 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":1}", 39, 0 },  /* 259 */
	{ "{\"body\":{\"0\":null},\"id\":\"\",\"type\":\"\"}", 37, 0 },  /* 260 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 108, 0 },  /* 261 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.connect\",\"0\":null}", 109, 0 },  /* 262 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"type\":\"kdeconnect.connect\",\"0\":null}", 69, 0 },  /* 263 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.connect\"}", 120, 0 },  /* 264 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 147, 1 },  /* 265 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 110, 0 },  /* 266 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":[]}", 48, 0 },  /* 267 */
	{ "{\"body\":\"\",\"id\":\"\",\"type\":\"\",\"0\":null}", 38, 0 },  /* 268 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 82, 0 },  /* 269 */
	{ "{\"id\":[null,null],\"type\":[null,null],\"0\":null}", 46, 0 },  /* 270 */
	{ "{\"body\":{\"content\":[null]},\"id\":[null,null]}", 44, 0 },  /* 271 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"id\":[]}", 71, 0 },  /* 272 */
	{ "{\"body\":{\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 86, 0 },  /* 273 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 116, 0 },  /* 274 */
	{ "{\"body\":{\"content\":null},\"id\":\"\",\"0\":null}", 42, 0 },  /* 275 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"type\":[],\"0\":null}", 59, 0 },  /* 276 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1}", 91, 0 },  /* 277 */
	{ "{\"body\":null,\"id\":null,\"type\":null}", 35, 0 },  /* 278 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":[],\"type\":[]}", 58, 0 },  /* 279 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"id\":{}}", 71, 0 },  /* 280 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"type\":[]}", 73, 0 },  /* 281 */
	{ "{\"body\":{\"content\":[null,null],\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 89, 0 },  /* 282 */
	{ "{\"body\":{\"content\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 52, 0 },  /* 283 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":0,\"0\":null}", 60, 0 },  /* 284 */
	{ "{\"body\":{\"content\":[null]},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 103, 0 },  /* 285 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 130, 0 },  /* 286 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":[null,null],\"type\":[null,null]}", 68, 0 },  /* 287 */
	{ "{}", 2, 0 },  /* 288 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 101, 0 },  /* 289 */
	{ "{\"body\":[null,null],\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 87, 0 },  /* 290 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 82, 0 },  /* 291 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":0}", 51, 0 },  /* 292 */
	{ "{\"body\":[null],\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 86, 0 },  /* 293 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 134, 0 },  /* 294 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 114, 0 },  /* 295 */
	{ "{\"body\":[null],\"type\":null,\"0\":null}", 36, 0 },  /* 296 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 91, 0 },  /* 297 */
	{ "{\"body\":null,\"type\":null}", 25, 0 },  /* 298 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{},\"type\":{}}", 54, 0 },  /* 299 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{}}", 82, 0 },  /* 300 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":[null]}", 46, 0 },  /* 301 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null}}", 97, 0 },  /* 302 */
	{ "null", 4, 0 },  /* 303 */
	{ "{\"body\":\"\",\"id\":\"\"}", 19, 0 },  /* 304 */
	{ "{\"id\":[null,null],\"type\":[null,null]}", 37, 0 },  /* 305 */
	{ "[null,null]", 11, 0 },  /* 306 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":{\"0\":null}}", 48, 0 },  /* 307 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":[],\"0\":null}", 49, 0 },  /* 308 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.connect\",\"additionalProperties-test-unique\":null}", 160, 0 },  /* 309 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null]}", 53, 0 },  /* 310 */
	{ "{\"body\":{},\"id\":[null]}", 23, 0 },  /* 311 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 86, 0 },  /* 312 */
	{ "{\"body\":{\"content\":\"\"},\"type\":\"kdeconnect.connect\",\"0\":null}", 60, 0 },  /* 313 */
	{ "[null]", 6, 0 },  /* 314 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 90, 0 },  /* 315 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"type\":\"kdeconnect.connect\"}", 60, 0 },  /* 316 */
	{ "{\"body\":[null,null],\"id\":{}}", 28, 0 },  /* 317 */
	{ "{\"id\":[],\"type\":\"kdeconnect.connect\",\"0\":null}", 46, 0 },  /* 318 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 124, 0 },  /* 319 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null,null],\"type\":[null,null]}", 67, 0 },  /* 320 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 105, 0 },  /* 321 */
	{ "{\"body\":{\"content\":\"\"},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null}", 67, 1 },  /* 322 */
	{ "{\"body\":[null,null],\"id\":{},\"type\":{},\"0\":null}", 47, 0 },  /* 323 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 99, 0 },  /* 324 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"0\":null}", 99, 0 },  /* 325 */
	{ "{\"body\":[null],\"id\":null,\"0\":null}", 34, 0 },  /* 326 */
	{ "{\"body\":{\"content\":\"\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null}", 107, 1 },  /* 327 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 129, 0 },  /* 328 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\"}", 119, 1 },  /* 329 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 159, 1 },  /* 330 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 119, 1 },  /* 331 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 78, 0 },  /* 332 */
	{ "{\"body\":{\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 46, 0 },  /* 333 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"0\":null}", 98, 0 },  /* 334 */
	{ "{\"id\":0,\"type\":\"kdeconnect.connect\",\"0\":null}", 45, 0 },  /* 335 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":1,\"0\":null}", 47, 0 },  /* 336 */
	{ "{\"body\":{\"0\":null},\"id\":\"\",\"0\":null}", 36, 0 },  /* 337 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"type\":[null],\"0\":null}", 64, 0 },  /* 338 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.connect\",\"0\":null}", 119, 1 },  /* 339 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 107, 0 },  /* 340 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"type\":[]}", 50, 0 },  /* 341 */
	{ "{\"body\":{\"content\":null},\"type\":\"\",\"0\":null}", 44, 0 },  /* 342 */
	{ "{\"body\":{\"content\":{},\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 81, 0 },  /* 343 */
	{ "{\"body\":{\"content\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 154, 0 },  /* 344 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{\"0\":null}}", 92, 0 },  /* 345 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 125, 0 },  /* 346 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 93, 0 },  /* 347 */
	{ "{\"body\":{\"content\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 141, 0 },  /* 348 */
	{ "{\"body\":{\"content\":[],\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 130, 0 },  /* 349 */
	{ "{\"id\":null,\"type\":null}", 23, 0 },  /* 350 */
	{ "{\"body\":{\"content\":[null]},\"id\":[null,null],\"type\":[null,null]}", 63, 0 },  /* 351 */
	{ "{\"body\":{\"content\":[null],\"additionalProperties-test-unique\":null},\"id\":null}", 77, 0 },  /* 352 */
	{ "{\"body\":[null],\"id\":null,\"type\":null,\"0\":null}", 46, 0 },  /* 353 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":1,\"type\":\"kdeconnect.connect\"}", 66, 0 },  /* 354 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 100, 0 },  /* 355 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 138, 0 },  /* 356 */
	{ "{\"body\":{\"content\":\"test content\",\"additionalProperties-test-unique\":null},\"id\":1}", 82, 0 },  /* 357 */
	{ "{\"body\":[],\"type\":\"\",\"0\":null}", 30, 0 },  /* 358 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 108, 0 },  /* 359 */
	{ "\342\230\240", 3, 0 },  /* 360 */
};
