/* Generated by json-schema-generate. Do not modify. */

#include <stddef.h>

static const struct { const char *json; size_t size; unsigned int is_valid; } clipboard_connect_fuzz[] = {
	{ "{\"body\":{\"timestamp\":1},\"id\":null,\"type\":null,\"0\":null}", 55, 0 },  /* 0 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"id\":null,\"0\":null}", 52, 0 },  /* 1 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 77, 0 },  /* 2 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"id\":null}", 56, 0 },  /* 3 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 101, 0 },  /* 4 */
	{ "{\"body\":{\"timestamp\":null},\"id\":{}}", 35, 0 },  /* 5 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"type\":[null],\"0\":null}", 57, 0 },  /* 6 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"id\":0,\"0\":null}", 65, 0 },  /* 7 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[]}", 94, 0 },  /* 8 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":null}", 50, 0 },  /* 9 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 10 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"type\":\"\",\"0\":null}", 51, 0 },  /* 11 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"type\":[null]}", 61, 0 },  /* 12 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 99, 0 },  /* 13 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"type\":[null,null]}", 68, 0 },  /* 14 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 105, 0 },  /* 15 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 104, 0 },  /* 16 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"id\":\"\",\"0\":null}", 50, 0 },  /* 17 */
	{ "{\"body\":{\"timestamp\":{}},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 91, 0 },  /* 18 */
	{ "{\"body\":{\"timestamp\":1},\"id\":null,\"type\":null}", 46, 0 },  /* 19 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null,\"0\":null}", 54, 0 },  /* 20 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 105, 0 },  /* 21 */
	{ "{\"body\":{\"content\":[null,null]},\"type\":{}}", 42, 0 },  /* 22 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 90, 0 },  /* 23 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 104, 0 },  /* 24 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 145, 0 },  /* 25 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 110, 0 },  /* 26 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 162, 0 },  /* 27 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"0\":null}", 112, 0 },  /* 28 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"type\":\"kdeconnect.clipboard.connect\"}", 75, 0 },  /* 29 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"id\":[null],\"0\":null}", 55, 0 },  /* 30 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"type\":null}", 77, 0 },  /* 31 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"type\":{},\"0\":null}", 61, 0 },  /* 32 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"type\":[]}", 44, 0 },  /* 33 */
	{ "{\"id\":[],\"type\":\"kdeconnect.clipboard.connect\"}", 47, 0 },  /* 34 */
	{ "{\"body\":{\"content\":[null]},\"id\":null,\"type\":null,\"0\":null}", 58, 0 },  /* 35 */
	{ "{\"body\":{\"timestamp\":[]},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 59, 0 },  /* 36 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 112, 1 },  /* 37 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":[]}", 94, 0 },  /* 38 */
	{ "{\"body\":{\"timestamp\":[null]},\"id\":[null,null],\"0\":null}", 55, 0 },  /* 39 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 99, 0 },  /* 40 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 82, 1 },  /* 41 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 98, 0 },  /* 42 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"id\":1}", 65, 0 },  /* 43 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 153, 0 },  /* 44 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null}}", 103, 0 },  /* 45 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":null,\"type\":null}", 66, 0 },  /* 46 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 169, 0 },  /* 47 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"id\":[],\"0\":null}", 64, 0 },  /* 48 */
	{ "{\"body\":{\"content\":[]},\"id\":[],\"type\":[],\"0\":null}", 50, 0 },  /* 49 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 108, 0 },  /* 50 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"id\":null}", 47, 0 },  /* 51 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"type\":null,\"0\":null}", 67, 0 },  /* 52 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"type\":[null,null],\"0\":null}", 77, 0 },  /* 53 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 91, 0 },  /* 54 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"id\":{\"0\":null},\"0\":null}", 59, 0 },  /* 55 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"type\":\"\",\"0\":null}", 53, 0 },  /* 56 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"id\":{},\"type\":{},\"0\":null}", 69, 0 },  /* 57 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 170, 0 },  /* 58 */
	{ "{\"body\":{\"content\":null},\"type\":{},\"0\":null}", 44, 0 },  /* 59 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 122, 0 },  /* 60 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"type\":\"\"}", 43, 0 },  /* 61 */
	{ "{\"id\":null,\"type\":null}", 23, 0 },  /* 62 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 171, 0 },  /* 63 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 113, 0 },  /* 64 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"id\":\"\",\"0\":null}", 51, 0 },  /* 65 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 117, 0 },  /* 66 */
	{ "{\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 46, 0 },  /* 67 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 114, 0 },  /* 68 */
	{ "{\"body\":{\"timestamp\":1},\"type\":null,\"0\":null}", 45, 0 },  /* 69 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null]}", 82, 0 },  /* 70 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\"}", 104, 0 },  /* 71 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null],\"0\":null}", 52, 0 },  /* 72 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 98, 0 },  /* 73 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 183, 1 },  /* 74 */
	{ "{\"body\":null,\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 71, 0 },  /* 75 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 153, 0 },  /* 76 */
	{ "{\"body\":{\"content\":null},\"id\":{},\"type\":{},\"0\":null}", 52, 0 },  /* 77 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"type\":[null,null]}", 60, 0 },  /* 78 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"id\":{}}", 54, 0 },  /* 79 */
	{ "{\"body\":[null,null],\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 96, 0 },  /* 80 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"type\":[null,null]}", 65, 0 },  /* 81 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"id\":\"\",\"type\":\"\",\"0\":null}", 67, 0 },  /* 82 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"type\":null}", 58, 0 },  /* 83 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 116, 0 },  /* 84 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 192, 1 },  /* 85 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 72, 0 },  /* 86 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"type\":{\"0\":null},\"0\":null}", 113, 0 },  /* 87 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"id\":{\"0\":null}}", 52, 0 },  /* 88 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\"}", 124, 0 },  /* 89 */
	{ "{\"body\":null,\"id\":\"\",\"0\":null}", 30, 0 },  /* 90 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 147, 0 },  /* 91 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":[],\"type\":[]}", 53, 0 },  /* 92 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 102, 0 },  /* 93 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 110, 0 },  /* 94 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"id\":[]}", 42, 0 },  /* 95 */
	{ "{\"body\":{\"content\":[null,null]},\"type\":{},\"0\":null}", 51, 0 },  /* 96 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 70, 0 },  /* 97 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":{},\"type\":{},\"0\":null}", 59, 0 },  /* 98 */
	{ "{\"body\":{\"timestamp\":0},\"id\":{\"0\":null}}", 40, 0 },  /* 99 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 132, 0 },  /* 100 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 101, 0 },  /* 101 */
	{ "{\"id\":0,\"type\":[]}", 18, 0 },  /* 102 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\"}", 51, 0 },  /* 103 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\"}", 115, 0 },  /* 104 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":[]}", 87, 0 },  /* 105 */
	{ "{\"body\":{\"content\":[null]},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 89, 0 },  /* 106 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"id\":null,\"type\":null,\"0\":null}", 64, 0 },  /* 107 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 108 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":\"\",\"type\":\"\"}", 50, 0 },  /* 109 */
	{ "{\"body\":{},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 82, 0 },  /* 110 */
	{ "{\"id\":\"\",\"type\":\"\",\"0\":null}", 28, 0 },  /* 111 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 113, 0 },  /* 112 */
	{ "{\"id\":[null],\"type\":[null],\"0\":null}", 36, 0 },  /* 113 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\"}", 114, 0 },  /* 114 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"type\":{\"0\":null}}", 74, 0 },  /* 115 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 131, 1 },  /* 116 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"id\":{\"0\":null},\"0\":null}", 63, 0 },  /* 117 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"id\":[],\"type\":[],\"0\":null}", 78, 0 },  /* 118 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"id\":null,\"type\":null,\"0\":null}", 96, 0 },  /* 119 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 139, 0 },  /* 120 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 121 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"id\":null,\"type\":null}", 87, 0 },  /* 122 */
	{ "{\"body\":[null,null],\"id\":[null,null]}", 37, 0 },  /* 123 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"type\":\"kdeconnect.clipboard.connect\"}", 84, 0 },  /* 124 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"type\":{},\"0\":null}", 61, 0 },  /* 125 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 118, 0 },  /* 126 */
	{ "{\"body\":{\"timestamp\":{}},\"type\":[null],\"0\":null}", 48, 0 },  /* 127 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"type\":[null]}", 109, 0 },  /* 128 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 121, 0 },  /* 129 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 109, 0 },  /* 130 */
	{ "{\"body\":{},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 73, 0 },  /* 131 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 114, 0 },  /* 132 */
	{ "{\"id\":null,\"type\":null,\"0\":null}", 32, 0 },  /* 133 */
	{ "{\"body\":{},\"type\":null,\"0\":null}", 32, 0 },  /* 134 */
	{ "{\"body\":{\"timestamp\":0},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 98, 0 },  /* 135 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"id\":0}", 65, 0 },  /* 136 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":null,\"0\":null}", 59, 0 },  /* 137 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":{}}", 88, 0 },  /* 138 */
	{ "{\"body\":{\"content\":null},\"id\":{},\"type\":{}}", 43, 0 },  /* 139 */
	{ "{\"body\":{\"content\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 83, 0 },  /* 140 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 90, 0 },  /* 141 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":\"\"}", 105, 0 },  /* 142 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null]}", 43, 0 },  /* 143 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":1,\"0\":null}", 52, 0 },  /* 144 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 99, 0 },  /* 145 */
	{ "{\"id\":[],\"type\":[],\"0\":null}", 28, 0 },  /* 146 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 107, 0 },  /* 147 */
	{ "{\"body\":{\"content\":[]},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 90, 0 },  /* 148 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null]}", 73, 0 },  /* 149 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"id\":{\"0\":null}}", 50, 0 },  /* 150 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"0\":null}", 42, 0 },  /* 151 */
	{ "{\"id\":\"\",\"type\":\"\"}", 19, 0 },  /* 152 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 162, 0 },  /* 153 */
	{ "{\"body\":{\"timestamp\":{}},\"id\":[null],\"type\":[null],\"0\":null}", 60, 0 },  /* 154 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 164, 0 },  /* 155 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"0\":null}", 103, 0 },  /* 156 */
	{ "{\"body\":{\"content\":[]},\"id\":[],\"type\":[]}", 41, 0 },  /* 157 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 76, 0 },  /* 158 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 120, 0 },  /* 159 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 105, 0 },  /* 160 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\"}", 94, 0 },  /* 161 */
	{ "{\"body\":{\"timestamp\":\"\"},\"id\":[null,null],\"0\":null}", 51, 0 },  /* 162 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\"}", 127, 0 },  /* 163 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 94, 0 },  /* 164 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 113, 0 },  /* 165 */
	{ "{\"body\":{\"timestamp\":0},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 67, 0 },  /* 166 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"type\":{\"0\":null}}", 51, 0 },  /* 167 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 116, 0 },  /* 168 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"id\":0}", 53, 0 },  /* 169 */
	{ "{\"body\":{\"timestamp\":[]},\"id\":{\"0\":null},\"0\":null}", 50, 0 },  /* 170 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"id\":[],\"0\":null}", 67, 0 },  /* 171 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 183, 1 },  /* 172 */
	{ "{\"body\":{\"timestamp\":\"\"},\"type\":[null,null]}", 44, 0 },  /* 173 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 124, 0 },  /* 174 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\"}", 113, 0 },  /* 175 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 161, 0 },  /* 176 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 93, 0 },  /* 177 */
	{ "{\"body\":{\"content\":[]},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 81, 0 },  /* 178 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 141, 0 },  /* 179 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null}", 45, 0 },  /* 180 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 90, 0 },  /* 181 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 96, 0 },  /* 182 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":\"\"}", 104, 0 },  /* 183 */
	{ "{\"body\":[null],\"id\":[null,null],\"type\":[null,null],\"0\":null}", 60, 0 },  /* 184 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\",\"0\":null}", 60, 0 },  /* 185 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 101, 0 },  /* 186 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 106, 0 },  /* 187 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"0\":null}", 110, 0 },  /* 188 */
	{ "{\"body\":[null,null],\"id\":[null,null],\"0\":null}", 46, 0 },  /* 189 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"type\":[]}", 57, 0 },  /* 190 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 103, 0 },  /* 191 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 59, 0 },  /* 192 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"type\":\"\"}", 50, 0 },  /* 193 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 96, 0 },  /* 194 */
	{ "{\"body\":[],\"id\":[null],\"0\":null}", 32, 0 },  /* 195 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 113, 0 },  /* 196 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 68, 0 },  /* 197 */
	{ "{\"body\":null,\"id\":\"\",\"type\":\"\",\"0\":null}", 40, 0 },  /* 198 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"id\":null,\"type\":null,\"0\":null}", 68, 0 },  /* 199 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"type\":[null,null],\"0\":null}", 74, 0 },  /* 200 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 103, 1 },  /* 201 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":[null],\"0\":null}", 116, 0 },  /* 202 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 122, 0 },  /* 203 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"id\":\"\",\"type\":\"\",\"0\":null}", 61, 0 },  /* 204 */
	{ "{\"body\":{\"timestamp\":[]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 108, 0 },  /* 205 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 192, 1 },  /* 206 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 162, 0 },  /* 207 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 152, 1 },  /* 208 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"type\":{}}", 105, 0 },  /* 209 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"type\":{\"0\":null},\"0\":null}", 61, 0 },  /* 210 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 152, 1 },  /* 211 */
	{ "{\"id\":[null,null],\"type\":[null,null]}", 37, 0 },  /* 212 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"type\":null}", 49, 0 },  /* 213 */
	{ "{\"body\":{\"content\":[null]},\"type\":null,\"0\":null}", 48, 0 },  /* 214 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\"}", 103, 0 },  /* 215 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":\"\",\"0\":null}", 105, 0 },  /* 216 */
	{ "{\"body\":{\"timestamp\":{}},\"id\":[null]}", 37, 0 },  /* 217 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":null,\"0\":null}", 63, 0 },  /* 218 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"id\":{},\"0\":null}", 59, 0 },  /* 219 */
	{ "{\"body\":[null,null],\"type\":[null,null],\"0\":null}", 48, 0 },  /* 220 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":{}}", 90, 0 },  /* 221 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1}", 93, 0 },  /* 222 */
	{ "{\"body\":{\"timestamp\":[null]},\"type\":[null,null]}", 48, 0 },  /* 223 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 121, 0 },  /* 224 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null]}", 121, 0 },  /* 225 */
	{ "{\"id\":{},\"type\":{},\"0\":null}", 28, 0 },  /* 226 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"type\":[null],\"0\":null}", 118, 0 },  /* 227 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"type\":\"\",\"0\":null}", 51, 0 },  /* 228 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null}", 118, 0 },  /* 229 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 153, 0 },  /* 230 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 133, 0 },  /* 231 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\"}", 136, 0 },  /* 232 */
	{ "{\"id\":[null,null],\"type\":[null,null],\"0\":null}", 46, 0 },  /* 233 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"id\":\"\"}", 41, 0 },  /* 234 */
	{ "{\"body\":[],\"type\":[null]}", 25, 0 },  /* 235 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 105, 0 },  /* 236 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":null,\"type\":null,\"0\":null}", 75, 0 },  /* 237 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 107, 0 },  /* 238 */
	{ "[]", 2, 0 },  /* 239 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 149, 0 },  /* 240 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":[],\"0\":null}", 52, 0 },  /* 241 */
	{ "{\"body\":[null],\"id\":[null,null],\"type\":[null,null]}", 51, 0 },  /* 242 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":\"\"}", 40, 0 },  /* 243 */
	{ "{\"body\":{\"timestamp\":1},\"id\":null,\"0\":null}", 43, 0 },  /* 244 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"id\":0,\"0\":null}", 62, 0 },  /* 245 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\"}", 73, 0 },  /* 246 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":[null],\"0\":null}", 112, 0 },  /* 247 */
	{ "{\"body\":[null],\"id\":[null,null]}", 32, 0 },  /* 248 */
	{ "{\"body\":{\"content\":\"\"},\"type\":[null],\"0\":null}", 46, 0 },  /* 249 */
	{ "{\"body\":[],\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 77, 0 },  /* 250 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 172, 0 },  /* 251 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"id\":[null],\"type\":[null],\"0\":null}", 81, 0 },  /* 252 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 103, 1 },  /* 253 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"id\":null}", 43, 0 },  /* 254 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"id\":[],\"type\":[],\"0\":null}", 77, 0 },  /* 255 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"id\":[],\"type\":[]}", 68, 0 },  /* 256 */
	{ "{\"body\":{\"content\":\"\"},\"id\":[null],\"type\":[null]}", 49, 0 },  /* 257 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"type\":[null],\"0\":null}", 101, 0 },  /* 258 */
	{ "{\"body\":\"\",\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 86, 0 },  /* 259 */
	{ "{\"body\":[null,null],\"type\":[null,null]}", 39, 0 },  /* 260 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 181, 0 },  /* 261 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[]}", 65, 0 },  /* 262 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 181, 0 },  /* 263 */
	{ "{\"body\":\"\",\"id\":[null],\"type\":[null],\"0\":null}", 46, 0 },  /* 264 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":1}", 105, 0 },  /* 265 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 98, 0 },  /* 266 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"type\":{\"0\":null}}", 54, 0 },  /* 267 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"type\":null,\"0\":null}", 86, 0 },  /* 268 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.clipboard.connect\"}", 132, 0 },  /* 269 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 175, 0 },  /* 270 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 102, 0 },  /* 271 */
	{ "{\"body\":{\"content\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 92, 0 },  /* 272 */
	{ "{\"body\":{\"content\":[]},\"type\":[]}", 33, 0 },  /* 273 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 136, 0 },  /* 274 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"id\":{\"0\":null},\"0\":null}", 80, 0 },  /* 275 */
	{ "{\"body\":{\"timestamp\":null},\"type\":{}}", 37, 0 },  /* 276 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"id\":\"\",\"0\":null}", 72, 0 },  /* 277 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 110, 0 },  /* 278 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"type\":\"\",\"0\":null}", 59, 0 },  /* 279 */
	{ "{\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 55, 0 },  /* 280 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":{\"0\":null}}", 102, 0 },  /* 281 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"type\":\"\"}", 106, 0 },  /* 282 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 83, 0 },  /* 283 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"type\":{\"0\":null}}", 73, 0 },  /* 284 */
	{ "{\"body\":[null,null],\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 105, 0 },  /* 285 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"type\":[],\"0\":null}", 69, 0 },  /* 286 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 109, 0 },  /* 287 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 67, 0 },  /* 288 */
	{ "{\"body\":[null],\"type\":[null,null]}", 34, 0 },  /* 289 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 131, 1 },  /* 290 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 124, 0 },  /* 291 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":[null]}", 107, 0 },  /* 292 */
	{ "{\"body\":{\"content\":null},\"type\":{}}", 35, 0 },  /* 293 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 107, 0 },  /* 294 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 97, 0 },  /* 295 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 84, 0 },  /* 296 */
	{ "{\"body\":{\"content\":\"\"},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 98, 0 },  /* 297 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"type\":[]}", 65, 0 },  /* 298 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"type\":{\"0\":null},\"0\":null}", 114, 0 },  /* 299 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":{}}", 90, 0 },  /* 300 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"id\":null}", 75, 0 },  /* 301 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 126, 0 },  /* 302 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 134, 1 },  /* 303 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":[]}", 99, 0 },  /* 304 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 122, 0 },  /* 305 */
	{ "{\"body\":{},\"id\":null}", 21, 0 },  /* 306 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"type\":\"kdeconnect.clipboard.connect\"}", 87, 0 },  /* 307 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"type\":{}}", 52, 0 },  /* 308 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"id\":{},\"type\":{}}", 60, 0 },  /* 309 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null]}", 101, 0 },  /* 310 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{}}", 103, 0 },  /* 311 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 117, 0 },  /* 312 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"id\":null,\"type\":null}", 68, 0 },  /* 313 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"id\":[],\"0\":null}", 51, 0 },  /* 314 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null],\"0\":null}", 69, 0 },  /* 315 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"id\":\"\",\"0\":null}", 57, 0 },  /* 316 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 105, 0 },  /* 317 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"id\":[],\"0\":null}", 72, 0 },  /* 318 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 143, 1 },  /* 319 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 97, 0 },  /* 320 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"id\":\"\",\"type\":\"\"}", 52, 0 },  /* 321 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 100, 0 },  /* 322 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 115, 0 },  /* 323 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":{},\"type\":{},\"0\":null}", 61, 0 },  /* 324 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 114, 0 },  /* 325 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 161, 0 },  /* 326 */
	{ "{\"body\":[],\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 86, 0 },  /* 327 */
	{ "{\"body\":\"\",\"id\":[null]}", 23, 0 },  /* 328 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 122, 1 },  /* 329 */
	{ "{\"id\":[],\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 56, 0 },  /* 330 */
	{ "{\"body\":{},\"type\":null}", 23, 0 },  /* 331 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"id\":[],\"type\":[],\"0\":null}", 70, 0 },  /* 332 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 118, 0 },  /* 333 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"id\":{\"0\":null},\"0\":null}", 81, 0 },  /* 334 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 140, 1 },  /* 335 */
	{ "{\"body\":{\"content\":{}},\"id\":null}", 33, 0 },  /* 336 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"type\":[null]}", 60, 0 },  /* 337 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 96, 0 },  /* 338 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 122, 0 },  /* 339 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 129, 0 },  /* 340 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"0\":null}", 103, 0 },  /* 341 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"type\":null,\"0\":null}", 65, 0 },  /* 342 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"type\":\"kdeconnect.clipboard.connect\"}", 96, 0 },  /* 343 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 91, 0 },  /* 344 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":0}", 96, 0 },  /* 345 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"type\":[],\"0\":null}", 53, 0 },  /* 346 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"id\":{},\"0\":null}", 63, 0 },  /* 347 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 160, 0 },  /* 348 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 113, 0 },  /* 349 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 158, 0 },  /* 350 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\"}", 136, 0 },  /* 351 */
	{ "{\"body\":\"\",\"type\":[null]}", 25, 0 },  /* 352 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"0\":null}", 112, 0 },  /* 353 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[],\"0\":null}", 61, 0 },  /* 354 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"type\":[null]}", 48, 0 },  /* 355 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 92, 0 },  /* 356 */
	{ "{\"body\":{\"content\":\"\"},\"id\":[null],\"0\":null}", 44, 0 },  /* 357 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 114, 0 },  /* 358 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null,null],\"type\":[null,null]}", 77, 0 },  /* 359 */
	{ "{\"body\":[null],\"id\":[null,null],\"0\":null}", 41, 0 },  /* 360 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":[null]}", 103, 0 },  /* 361 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 153, 0 },  /* 362 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"type\":{\"0\":null},\"0\":null}", 82, 0 },  /* 363 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 106, 0 },  /* 364 */
	{ "{\"body\":[null],\"type\":[null,null],\"0\":null}", 43, 0 },  /* 365 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"id\":{\"0\":null}}", 49, 0 },  /* 366 */
	{ "{\"body\":{\"content\":\"\"},\"id\":[null],\"type\":[null],\"0\":null}", 58, 0 },  /* 367 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 154, 0 },  /* 368 */
	{ "{\"body\":[],\"type\":[null],\"0\":null}", 34, 0 },  /* 369 */
	{ "{\"body\":{\"timestamp\":\"\"},\"id\":[null,null]}", 42, 0 },  /* 370 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 130, 0 },  /* 371 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"id\":[null]}", 59, 0 },  /* 372 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":\"\",\"type\":\"\"}", 50, 0 },  /* 373 */
	{ "{\"body\":{\"timestamp\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 94, 0 },  /* 374 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"type\":\"\"}", 42, 0 },  /* 375 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null],\"type\":[null]}", 57, 0 },  /* 376 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"type\":[null],\"0\":null}", 70, 0 },  /* 377 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 131, 0 },  /* 378 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\"}", 134, 1 },  /* 379 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"id\":\"\"}", 63, 0 },  /* 380 */
	{ "{\"body\":{\"timestamp\":[]},\"id\":{\"0\":null}}", 41, 0 },  /* 381 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 131, 1 },  /* 382 */
	{ "{\"body\":{\"content\":[]},\"type\":[],\"0\":null}", 42, 0 },  /* 383 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"type\":null,\"0\":null}", 54, 0 },  /* 384 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 108, 0 },  /* 385 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":{}}", 40, 0 },  /* 386 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 98, 0 },  /* 387 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"id\":null,\"type\":null}", 55, 0 },  /* 388 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 89, 0 },  /* 389 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"type\":{}}", 96, 0 },  /* 390 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"id\":{\"0\":null}}", 54, 0 },  /* 391 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 127, 0 },  /* 392 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"type\":{\"0\":null}}", 52, 0 },  /* 393 */
	{ "{\"body\":{\"timestamp\":0},\"id\":{\"0\":null},\"0\":null}", 49, 0 },  /* 394 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 115, 0 },  /* 395 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"id\":0,\"0\":null}", 74, 0 },  /* 396 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 109, 0 },  /* 397 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":[null]}", 90, 0 },  /* 398 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{\"0\":null},\"0\":null}", 61, 0 },  /* 399 */
	{ "{\"body\":{},\"id\":null,\"type\":null}", 33, 0 },  /* 400 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 163, 0 },  /* 401 */
	{ "{\"body\":{},\"id\":null,\"0\":null}", 30, 0 },  /* 402 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"id\":{},\"0\":null}", 59, 0 },  /* 403 */
	{ "{\"body\":{\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 101, 0 },  /* 404 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 122, 0 },  /* 405 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":{},\"0\":null}", 49, 0 },  /* 406 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 100, 0 },  /* 407 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null}", 130, 0 },  /* 408 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 92, 0 },  /* 409 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"id\":{},\"type\":{},\"0\":null}", 73, 0 },  /* 410 */
	{ "{\"body\":{\"timestamp\":{}},\"id\":[null],\"0\":null}", 46, 0 },  /* 411 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"type\":{}}", 52, 0 },  /* 412 */
	{ "{\"body\":{\"timestamp\":[]},\"type\":{\"0\":null},\"0\":null}", 52, 0 },  /* 413 */
	{ "{\"body\":{\"content\":[null]},\"id\":null,\"0\":null}", 46, 0 },  /* 414 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 85, 0 },  /* 415 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":\"\",\"0\":null}", 113, 0 },  /* 416 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 172, 0 },  /* 417 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 139, 0 },  /* 418 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 419 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null]},\"id\":null,\"0\":null}", 84, 0 },  /* 420 */
	{ "{\"body\":{\"timestamp\":null},\"id\":{},\"type\":{}}", 45, 0 },  /* 421 */
	{ "{\"body\":{\"content\":[null]},\"id\":null}", 37, 0 },  /* 422 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null,null],\"0\":null}", 67, 0 },  /* 423 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"id\":{\"0\":null},\"0\":null}", 58, 0 },  /* 424 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":null}", 89, 0 },  /* 425 */
	{ "{\"body\":{\"timestamp\":null},\"id\":{},\"type\":{},\"0\":null}", 54, 0 },  /* 426 */
	{ "{\"body\":{\"timestamp\":null},\"type\":{},\"0\":null}", 46, 0 },  /* 427 */
	{ "{\"body\":{\"content\":\"\"},\"id\":[null]}", 35, 0 },  /* 428 */
	{ "{\"body\":{\"content\":null},\"id\":{}}", 33, 0 },  /* 429 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"type\":[]}", 48, 0 },  /* 430 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"type\":[null]}", 92, 0 },  /* 431 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"type\":\"kdeconnect.clipboard.connect\"}", 96, 0 },  /* 432 */
	{ "{\"body\":{\"timestamp\":[null]},\"id\":[null,null]}", 46, 0 },  /* 433 */
	{ "{\"body\":{\"timestamp\":0},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 107, 0 },  /* 434 */
	{ "{\"body\":{\"content\":\"\"},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 89, 0 },  /* 435 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 133, 0 },  /* 436 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"type\":\"\",\"0\":null}", 52, 0 },  /* 437 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"type\":{},\"0\":null}", 53, 0 },  /* 438 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":\"\",\"0\":null}", 49, 0 },  /* 439 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null]}", 115, 0 },  /* 440 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 96, 0 },  /* 441 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"type\":\"\"}", 65, 0 },  /* 442 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"type\":[],\"0\":null}", 70, 0 },  /* 443 */
	{ "{\"body\":\"\",\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 77, 0 },  /* 444 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 152, 1 },  /* 445 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 112, 0 },  /* 446 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":{}}", 42, 0 },  /* 447 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 150, 0 },  /* 448 */
	{ "{\"body\":{\"content\":[]},\"id\":[],\"0\":null}", 40, 0 },  /* 449 */
	{ "{\"body\":\"\",\"id\":[null],\"type\":[null]}", 37, 0 },  /* 450 */
	{ "{\"body\":{\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 70, 0 },  /* 451 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"id\":[null]}", 58, 0 },  /* 452 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 138, 0 },  /* 453 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"type\":\"\",\"0\":null}", 74, 0 },  /* 454 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"type\":\"\",\"0\":null}", 51, 0 },  /* 455 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 122, 0 },  /* 456 */
	{ "{\"body\":{\"timestamp\":[null]},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 114, 0 },  /* 457 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 70, 0 },  /* 458 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"type\":{\"0\":null},\"0\":null}", 63, 0 },  /* 459 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"id\":[]}", 51, 0 },  /* 460 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 131, 0 },  /* 461 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 59, 0 },  /* 462 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"type\":{},\"0\":null}", 65, 0 },  /* 463 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 111, 0 },  /* 464 */
	{ "{\"body\":{\"timestamp\":[null]},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 105, 0 },  /* 465 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"type\":{\"0\":null},\"0\":null}", 83, 0 },  /* 466 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"type\":[]}", 53, 0 },  /* 467 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"id\":[],\"0\":null}", 55, 0 },  /* 468 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 109, 0 },  /* 469 */
	{ "{\"id\":[null],\"type\":[null]}", 27, 0 },  /* 470 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"id\":{\"0\":null}}", 72, 0 },  /* 471 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{}}", 94, 0 },  /* 472 */
	{ "{\"body\":{\"timestamp\":1},\"type\":null}", 36, 0 },  /* 473 */
	{ "{\"body\":{\"content\":\"test content\"},\"type\":[],\"0\":null}", 54, 0 },  /* 474 */
	{ "{\"body\":{\"timestamp\":\"\"},\"type\":[null,null],\"0\":null}", 53, 0 },  /* 475 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"type\":{\"0\":null},\"0\":null}", 65, 0 },  /* 476 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"id\":[null,null],\"0\":null}", 72, 0 },  /* 477 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"id\":{},\"type\":{}}", 64, 0 },  /* 478 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 136, 0 },  /* 479 */
	{ "{}", 2, 0 },  /* 480 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":\"\",\"0\":null}", 114, 0 },  /* 481 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"id\":null,\"type\":null,\"0\":null}", 77, 0 },  /* 482 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 112, 0 },  /* 483 */
	{ "{\"body\":{\"timestamp\":[]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 68, 0 },  /* 484 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 112, 0 },  /* 485 */
	{ "{\"body\":[null,null],\"id\":[null,null],\"type\":[null,null],\"0\":null}", 65, 0 },  /* 486 */
	{ "{\"body\":{\"timestamp\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 85, 0 },  /* 487 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 104, 0 },  /* 488 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"type\":\"\"}", 42, 0 },  /* 489 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"type\":{\"0\":null},\"0\":null}", 60, 0 },  /* 490 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 152, 1 },  /* 491 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"type\":[],\"0\":null}", 62, 0 },  /* 492 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 170, 0 },  /* 493 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"id\":[null]}", 46, 0 },  /* 494 */
	{ "{\"body\":{\"content\":[null]},\"type\":null}", 39, 0 },  /* 495 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\"},\"id\":[null,null]}", 63, 0 },  /* 496 */
	{ "{\"body\":[],\"id\":[null]}", 23, 0 },  /* 497 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 163, 0 },  /* 498 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"id\":1}", 44, 0 },  /* 499 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":null}", 87, 0 },  /* 500 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"type\":[null]}", 45, 0 },  /* 501 */
	{ "{\"body\":{\"content\":[]},\"id\":[]}", 31, 0 },  /* 502 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":{},\"type\":{}}", 52, 0 },  /* 503 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":\"\",\"0\":null}", 49, 0 },  /* 504 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 108, 0 },  /* 505 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1}", 105, 0 },  /* 506 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null]}", 60, 0 },  /* 507 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"id\":null,\"0\":null}", 56, 0 },  /* 508 */
	{ "{\"body\":{\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null]}", 61, 0 },  /* 509 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\"}", 91, 1 },  /* 510 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null}", 113, 0 },  /* 511 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 144, 0 },  /* 512 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 109, 0 },  /* 513 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 112, 1 },  /* 514 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null]}", 104, 0 },  /* 515 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 171, 1 },  /* 516 */
	{ "{\"body\":null,\"type\":\"\"}", 23, 0 },  /* 517 */
	{ "{\"body\":{\"timestamp\":[]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 99, 0 },  /* 518 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"id\":[null],\"type\":[null],\"0\":null}", 66, 0 },  /* 519 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 122, 0 },  /* 520 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 143, 0 },  /* 521 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 134, 0 },  /* 522 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"id\":[],\"type\":[]}", 69, 0 },  /* 523 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"id\":[]}", 55, 0 },  /* 524 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":[],\"type\":[],\"0\":null}", 62, 0 },  /* 525 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"type\":[],\"0\":null}", 74, 0 },  /* 526 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 103, 0 },  /* 527 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null}},\"id\":null,\"0\":null}", 65, 0 },  /* 528 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"id\":[],\"type\":[]}", 61, 0 },  /* 529 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 79, 0 },  /* 530 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 126, 0 },  /* 531 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"id\":\"\"}", 48, 0 },  /* 532 */
	{ "{\"body\":[null],\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 91, 0 },  /* 533 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 90, 0 },  /* 534 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 101, 0 },  /* 535 */
	{ "{\"body\":{\"timestamp\":1},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 86, 0 },  /* 536 */
	{ "{\"body\":[],\"id\":[null],\"type\":[null]}", 37, 0 },  /* 537 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 144, 0 },  /* 538 */
	{ "{\"body\":{\"content\":{}},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 94, 0 },  /* 539 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"type\":{\"0\":null}}", 104, 0 },  /* 540 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 81, 0 },  /* 541 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"type\":[]}", 60, 0 },  /* 542 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 135, 0 },  /* 543 */
	{ "{\"body\":{\"timestamp\":{}},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 100, 0 },  /* 544 */
	{ "{\"body\":{\"content\":null},\"id\":{},\"0\":null}", 42, 0 },  /* 545 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"type\":{\"0\":null}}", 54, 0 },  /* 546 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"type\":\"\",\"0\":null}", 115, 0 },  /* 547 */
	{ "{\"body\":null,\"id\":\"\",\"type\":\"\"}", 31, 0 },  /* 548 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 123, 0 },  /* 549 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 100, 0 },  /* 550 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 171, 1 },  /* 551 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"type\":[null],\"0\":null}", 69, 0 },  /* 552 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"id\":{\"0\":null},\"0\":null}", 61, 0 },  /* 553 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"id\":{},\"0\":null}", 51, 0 },  /* 554 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 143, 1 },  /* 555 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 143, 1 },  /* 556 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 117, 0 },  /* 557 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"id\":[]}", 63, 0 },  /* 558 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 143, 1 },  /* 559 */
	{ "{\"id\":{},\"type\":{}}", 19, 0 },  /* 560 */
	{ "{\"body\":{\"timestamp\":null},\"id\":{},\"0\":null}", 44, 0 },  /* 561 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 141, 0 },  /* 562 */
	{ "{\"body\":{\"content\":{}},\"type\":null}", 35, 0 },  /* 563 */
	{ "{\"body\":[],\"id\":[null],\"type\":[null],\"0\":null}", 46, 0 },  /* 564 */
	{ "{\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 55, 0 },  /* 565 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"id\":{}}", 50, 0 },  /* 566 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null,\"timestamp\":\"\"},\"id\":{\"0\":null}}", 71, 0 },  /* 567 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null]},\"type\":{}}", 56, 0 },  /* 568 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1},\"id\":1,\"0\":null}", 74, 0 },  /* 569 */
	{ "{\"body\":{},\"id\":null,\"type\":null,\"0\":null}", 42, 0 },  /* 570 */
	{ "{\"body\":{\"timestamp\":1},\"id\":null}", 34, 0 },  /* 571 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null,null]}", 58, 0 },  /* 572 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 104, 0 },  /* 573 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 102, 0 },  /* 574 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 93, 0 },  /* 575 */
	{ "{\"body\":\"\",\"id\":[null],\"0\":null}", 32, 0 },  /* 576 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\"}", 103, 1 },  /* 577 */
	{ "{\"body\":{\"timestamp\":0},\"type\":{\"0\":null},\"0\":null}", 51, 0 },  /* 578 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"type\":null}", 45, 0 },  /* 579 */
	{ "{\"id\":{\"0\":null},\"type\":{\"0\":null}}", 35, 0 },  /* 580 */
	{ "{\"body\":{\"content\":[null]},\"id\":null,\"type\":null}", 49, 0 },  /* 581 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[]},\"id\":\"\",\"type\":\"\"}", 58, 0 },  /* 582 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 183, 1 },  /* 583 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 144, 0 },  /* 584 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 190, 0 },  /* 585 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 81, 0 },  /* 586 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 100, 1 },  /* 587 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 90, 0 },  /* 588 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":null,\"type\":null}", 62, 0 },  /* 589 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"id\":[],\"0\":null}", 68, 0 },  /* 590 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 121, 0 },  /* 591 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 59, 0 },  /* 592 */
	{ "{\"body\":{\"timestamp\":{}},\"type\":[null]}", 39, 0 },  /* 593 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 130, 0 },  /* 594 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 113, 0 },  /* 595 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 109, 0 },  /* 596 */
	{ "{\"body\":null,\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 80, 0 },  /* 597 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 143, 1 },  /* 598 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"id\":[],\"type\":[],\"0\":null}", 82, 0 },  /* 599 */
	{ "{\"body\":{\"timestamp\":[null]},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 74, 0 },  /* 600 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 122, 0 },  /* 601 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 117, 0 },  /* 602 */
	{ "{\"body\":[null,null],\"id\":[null,null],\"type\":[null,null]}", 56, 0 },  /* 603 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"id\":[]}", 46, 0 },  /* 604 */
	{ "{\"id\":0,\"type\":\"kdeconnect.clipboard.connect\"}", 46, 0 },  /* 605 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0}", 84, 0 },  /* 606 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 101, 0 },  /* 607 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 148, 0 },  /* 608 */
	{ "{\"body\":{\"content\":{\"0\":null}},\"type\":[null],\"0\":null}", 54, 0 },  /* 609 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 174, 1 },  /* 610 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"id\":null,\"type\":null}", 59, 0 },  /* 611 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"id\":[null],\"0\":null}", 68, 0 },  /* 612 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"id\":[],\"type\":[]}", 56, 0 },  /* 613 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"id\":{}}", 50, 0 },  /* 614 */
	{ "{\"body\":{\"timestamp\":[null]},\"type\":[null,null],\"0\":null}", 57, 0 },  /* 615 */
	{ "{\"body\":{\"content\":\"\"},\"type\":[null]}", 37, 0 },  /* 616 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"type\":{}}", 92, 0 },  /* 617 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 140, 1 },  /* 618 */
	{ "{\"body\":{\"content\":null,\"0\":null},\"type\":{}}", 44, 0 },  /* 619 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null}", 124, 0 },  /* 620 */
	{ "{\"body\":{\"content\":{}},\"type\":null,\"0\":null}", 44, 0 },  /* 621 */
	{ "{\"body\":{\"content\":[null],\"0\":null,\"timestamp\":[null]},\"id\":[],\"type\":[]}", 73, 0 },  /* 622 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 105, 0 },  /* 623 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 153, 0 },  /* 624 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"type\":[null,null],\"0\":null}", 69, 0 },  /* 625 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":\"\"}", 96, 0 },  /* 626 */
	{ "{\"body\":[null],\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 100, 0 },  /* 627 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":null}", 54, 0 },  /* 628 */
	{ "{\"body\":{\"timestamp\":0},\"type\":{\"0\":null}}", 42, 0 },  /* 629 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"type\":null}", 56, 0 },  /* 630 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[],\"0\":null}", 74, 0 },  /* 631 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 129, 0 },  /* 632 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[]},\"id\":[]}", 58, 0 },  /* 633 */
	{ "null", 4, 0 },  /* 634 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 105, 0 },  /* 635 */
	{ "[null,null]", 11, 0 },  /* 636 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"id\":[null,null],\"type\":[null,null]}", 85, 0 },  /* 637 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"id\":[null,null],\"0\":null}", 75, 0 },  /* 638 */
	{ "{\"body\":{\"timestamp\":[]},\"type\":{\"0\":null}}", 43, 0 },  /* 639 */
	{ "{\"body\":{\"content\":{\"0\":null},\"timestamp\":\"\",\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 113, 0 },  /* 640 */
	{ "{\"body\":{\"timestamp\":1},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 95, 0 },  /* 641 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":\"\",\"0\":null}", 49, 0 },  /* 642 */
	{ "[null]", 6, 0 },  /* 643 */
	{ "{\"body\":{\"content\":\"test content\"},\"type\":[]}", 45, 0 },  /* 644 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 149, 0 },  /* 645 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 79, 0 },  /* 646 */
	{ "{\"body\":{\"content\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 138, 0 },  /* 647 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\"}", 122, 1 },  /* 648 */
	{ "{\"body\":{\"timestamp\":\"\"},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 110, 0 },  /* 649 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":\"\"}", 40, 0 },  /* 650 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"type\":\"\"}", 44, 0 },  /* 651 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 123, 0 },  /* 652 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"type\":[],\"0\":null}", 66, 0 },  /* 653 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 114, 0 },  /* 654 */
	{ "{\"body\":{\"content\":[null],\"timestamp\":[null],\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"0\":null}", 111, 0 },  /* 655 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 166, 0 },  /* 656 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":1}", 43, 0 },  /* 657 */
	{ "{\"body\":{\"content\":[null,null]},\"id\":{},\"type\":{}}", 50, 0 },  /* 658 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"additionalProperties-test-unique\":null}", 134, 0 },  /* 659 */
	{ "{\"body\":{\"content\":{},\"0\":null,\"timestamp\":{},\"additionalProperties-test-unique\":null},\"type\":{\"0\":null}}", 105, 0 },  /* 660 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 125, 0 },  /* 661 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"type\":[]}", 101, 0 },  /* 662 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"id\":[],\"0\":null}", 60, 0 },  /* 663 */
	{ "{\"body\":null,\"id\":\"\"}", 21, 0 },  /* 664 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{}},\"id\":[],\"type\":[]}", 52, 0 },  /* 665 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 86, 0 },  /* 666 */
	{ "{\"body\":{\"0\":null,\"timestamp\":{\"0\":null}},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 100, 0 },  /* 667 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"id\":[null],\"0\":null}", 67, 0 },  /* 668 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"type\":\"\"}", 42, 0 },  /* 669 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 131, 1 },  /* 670 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\"}", 94, 1 },  /* 671 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"type\":null}", 52, 0 },  /* 672 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"id\":[]}", 59, 0 },  /* 673 */
	{ "{\"body\":{\"0\":null,\"timestamp\":1},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 107, 0 },  /* 674 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 121, 0 },  /* 675 */
	{ "{\"body\":{\"content\":[null]},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 98, 0 },  /* 676 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 108, 0 },  /* 677 */
	{ "{\"id\":[],\"type\":[]}", 19, 0 },  /* 678 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"type\":{\"0\":null},\"0\":null}", 63, 0 },  /* 679 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 106, 0 },  /* 680 */
	{ "{\"body\":{\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 108, 0 },  /* 681 */
	{ "{\"body\":{\"timestamp\":{}},\"id\":[null],\"type\":[null]}", 51, 0 },  /* 682 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"0\":null}", 99, 0 },  /* 683 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null,\"additionalProperties-test-unique\":null}", 180, 1 },  /* 684 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null]},\"type\":{\"0\":null}}", 56, 0 },  /* 685 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 119, 0 },  /* 686 */
	{ "{\"body\":null,\"type\":\"\",\"0\":null}", 32, 0 },  /* 687 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 99, 0 },  /* 688 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[]},\"id\":[null,null]}", 66, 0 },  /* 689 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"id\":\"\"}", 42, 0 },  /* 690 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 103, 0 },  /* 691 */
	{ "{\"body\":{\"content\":[],\"timestamp\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 113, 0 },  /* 692 */
	{ "{\"body\":{\"0\":null,\"timestamp\":\"\"},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 92, 0 },  /* 693 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 112, 0 },  /* 694 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":1,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\"}", 143, 1 },  /* 695 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"id\":null,\"type\":null,\"0\":null}", 71, 0 },  /* 696 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\",\"0\":null}", 82, 0 },  /* 697 */
	{ "{\"body\":{\"timestamp\":0},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 58, 0 },  /* 698 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"id\":1,\"0\":null}", 53, 0 },  /* 699 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"type\":null,\"0\":null}", 58, 0 },  /* 700 */
	{ "{\"body\":{\"content\":[],\"timestamp\":1},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 108, 0 },  /* 701 */
	{ "{\"body\":{\"content\":[],\"0\":null,\"timestamp\":1},\"id\":[null],\"type\":[null]}", 72, 0 },  /* 702 */
	{ "{\"body\":{\"content\":[null,null],\"timestamp\":[null,null]},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 130, 0 },  /* 703 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"id\":{\"0\":null}}", 52, 0 },  /* 704 */
	{ "{\"body\":{\"timestamp\":{\"0\":null}},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 100, 0 },  /* 705 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 155, 0 },  /* 706 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0},\"id\":1,\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 91, 1 },  /* 707 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"type\":[],\"0\":null}", 57, 0 },  /* 708 */
	{ "{\"body\":{\"0\":null,\"timestamp\":0},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 95, 0 },  /* 709 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null},\"type\":[]}", 61, 0 },  /* 710 */
	{ "{\"body\":{\"content\":\"test content\",\"timestamp\":1},\"id\":0}", 56, 0 },  /* 711 */
	{ "{\"body\":\"\",\"type\":[null],\"0\":null}", 34, 0 },  /* 712 */
	{ "{\"body\":{\"content\":{},\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 713 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"id\":{},\"type\":{}}", 60, 0 },  /* 714 */
	{ "{\"body\":{\"content\":\"\",\"timestamp\":0,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.clipboard.connect\",\"additionalProperties-test-unique\":null}", 162, 1 },  /* 715 */
	{ "{\"body\":{\"0\":null,\"timestamp\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 119, 0 },  /* 716 */
	{ "{\"body\":{\"content\":\"test content\",\"0\":null,\"timestamp\":0,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 145, 0 },  /* 717 */
	{ "{\"body\":{\"content\":{\"0\":null},\"0\":null},\"type\":null,\"0\":null}", 61, 0 },  /* 718 */
	{ "\"\"", 2, 0 },  /* 719 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 140, 0 },  /* 720 */
	{ "{\"body\":{\"content\":null,\"timestamp\":null},\"id\":{},\"type\":{},\"0\":null}", 69, 0 },  /* 721 */
	{ "{\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 44, 0 },  /* 722 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":[]},\"id\":[null],\"type\":[null],\"0\":null}", 82, 0 },  /* 723 */
	{ "{\"body\":{\"content\":{},\"timestamp\":{}},\"id\":[],\"type\":[],\"0\":null}", 65, 0 },  /* 724 */
	{ "{\"body\":{\"content\":[null],\"0\":null},\"type\":\"kdeconnect.clipboard.connect\"}", 74, 0 },  /* 725 */
	{ "{\"body\":{\"content\":\"test content\"},\"id\":[]}", 43, 0 },  /* 726 */
	{ "{\"body\":{\"content\":[null,null],\"0\":null,\"timestamp\":[null,null],\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 131, 0 },  /* 727 */
	{ "{\"id\":0,\"type\":[],\"0\":null}", 27, 0 },  /* 728 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":\"\",\"type\":\"\"}", 50, 0 },  /* 729 */
	{ "{\"body\":{\"0\":null,\"timestamp\":[null,null]},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 110, 0 },  /* 730 */
	{ "{\"body\":{\"content\":null,\"0\":null,\"timestamp\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[]}", 109, 0 },  /* 731 */
	{ "{\"body\":{\"timestamp\":[null]},\"id\":[null,null],\"type\":[null,null]}", 65, 0 },  /* 732 */
	{ "{\"body\":{\"content\":\"\",\"0\":null,\"timestamp\":0},\"type\":\"kdeconnect.clipboard.connect\",\"0\":null}", 93, 0 },  /* 733 */
	{ "{\"body\":{\"content\":\"\",\"0\":null},\"id\":\"\"}", 40, 0 },  /* 734 */
	{ "{\"body\":{\"content\":[],\"0\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 90, 0 },  /* 735 */
	{ "\342\230\240", 3, 0 },  /* 736 */
};
