/* Generated by json-schema-generate. Do not modify. */

#include <stddef.h>

static const struct { const char *json; size_t size; unsigned int is_valid; } ping_fuzz[] = {
	{ "{\"body\":{\"message\":\"\"},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 64, 1 },  /* 0 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"id\":null,\"type\":null}", 53, 0 },  /* 1 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 147, 0 },  /* 2 */
	{ "{\"body\":{},\"id\":0,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 83, 1 },  /* 3 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 77, 0 },  /* 4 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 118, 0 },  /* 5 */
	{ "{\"body\":{},\"type\":\"kdeconnect.ping\"}", 36, 0 },  /* 6 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 100, 0 },  /* 7 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 113, 1 },  /* 8 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 107, 0 },  /* 9 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 122, 1 },  /* 10 */
	{ "{\"body\":null,\"type\":[]}", 23, 0 },  /* 11 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 91, 0 },  /* 12 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null}", 99, 0 },  /* 13 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"id\":[null]}", 75, 0 },  /* 14 */
	{ "{\"body\":\"\",\"type\":[],\"0\":null}", 30, 0 },  /* 15 */
	{ "{\"body\":[null,null],\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 94, 0 },  /* 16 */
	{ "{\"body\":{\"message\":[null,null]},\"id\":[],\"type\":[]}", 50, 0 },  /* 17 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null}", 98, 0 },  /* 18 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0}", 82, 0 },  /* 19 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 75, 0 },  /* 20 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 114, 0 },  /* 21 */
	{ "{\"body\":{\"message\":\"test message\"},\"id\":0,\"0\":null}", 51, 0 },  /* 22 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1}", 81, 0 },  /* 23 */
	{ "{\"body\":{\"0\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 53, 0 },  /* 24 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 156, 1 },  /* 25 */
	{ "{\"body\":{\"message\":[null]},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 72, 0 },  /* 26 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\"}", 76, 1 },  /* 27 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"id\":{},\"type\":{}}", 54, 0 },  /* 28 */
	{ "{\"id\":null,\"type\":null,\"0\":null}", 32, 0 },  /* 29 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"id\":0}", 39, 0 },  /* 30 */
	{ "{\"id\":0,\"type\":\"kdeconnect.ping\"}", 33, 0 },  /* 31 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 97, 0 },  /* 32 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[]}", 92, 0 },  /* 33 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 104, 1 },  /* 34 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 138, 0 },  /* 35 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 145, 0 },  /* 36 */
	{ "{\"body\":{\"message\":[]},\"id\":\"\",\"type\":\"\",\"0\":null}", 50, 0 },  /* 37 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 156, 1 },  /* 38 */
	{ "{\"body\":{\"message\":[]},\"id\":\"\",\"type\":\"\"}", 41, 0 },  /* 39 */
	{ "{\"body\":{\"message\":[]},\"id\":\"\",\"0\":null}", 40, 0 },  /* 40 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 91, 0 },  /* 41 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 100, 0 },  /* 42 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.ping\",\"0\":null}", 114, 0 },  /* 43 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{\"0\":null}}", 99, 0 },  /* 44 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 140, 1 },  /* 45 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 129, 0 },  /* 46 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 125, 0 },  /* 47 */
	{ "{\"body\":[null,null],\"id\":{\"0\":null},\"type\":{\"0\":null}}", 54, 0 },  /* 48 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 95, 0 },  /* 49 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"id\":0}", 57, 0 },  /* 50 */
	{ "{\"body\":{\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\"}", 51, 1 },  /* 51 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"id\":\"\"}", 49, 0 },  /* 52 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"type\":[null],\"0\":null}", 86, 0 },  /* 53 */
	{ "{\"body\":{\"message\":null},\"type\":{},\"0\":null}", 44, 0 },  /* 54 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"id\":[null]}", 44, 0 },  /* 55 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 153, 1 },  /* 56 */
	{ "{\"body\":{},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 92, 1 },  /* 57 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 146, 0 },  /* 58 */
	{ "{\"body\":null,\"id\":[],\"type\":[],\"0\":null}", 40, 0 },  /* 59 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 108, 0 },  /* 60 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 147, 1 },  /* 61 */
	{ "{\"body\":{},\"id\":0,\"0\":null}", 27, 0 },  /* 62 */
	{ "{\"body\":[null],\"id\":{},\"type\":{}}", 33, 0 },  /* 63 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 97, 0 },  /* 64 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"type\":{\"0\":null}}", 58, 0 },  /* 65 */
	{ "{\"body\":[null],\"id\":{},\"0\":null}", 32, 0 },  /* 66 */
	{ "[]", 2, 0 },  /* 67 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 117, 0 },  /* 68 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 150, 0 },  /* 69 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\"}", 91, 1 },  /* 70 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[]}", 82, 0 },  /* 71 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":null}", 88, 0 },  /* 72 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 116, 1 },  /* 73 */
	{ "{\"body\":{\"message\":\"\"},\"id\":1,\"0\":null}", 39, 0 },  /* 74 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 89, 0 },  /* 75 */
	{ "{\"body\":{\"message\":[null,null]},\"id\":[],\"type\":[],\"0\":null}", 59, 0 },  /* 76 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":null}", 81, 0 },  /* 77 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 66, 0 },  /* 78 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 90, 0 },  /* 79 */
	{ "{\"body\":{\"message\":[null,null]},\"type\":[],\"0\":null}", 51, 0 },  /* 80 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 130, 0 },  /* 81 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\"}", 82, 1 },  /* 82 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 165, 1 },  /* 83 */
	{ "{\"body\":\"\",\"id\":[],\"0\":null}", 28, 0 },  /* 84 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"type\":[null]}", 77, 0 },  /* 85 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 94, 0 },  /* 86 */
	{ "{\"body\":{\"message\":[null]},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 103, 0 },  /* 87 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 59, 0 },  /* 88 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"0\":null}", 84, 0 },  /* 89 */
	{ "{\"id\":\"\",\"type\":\"\",\"0\":null}", 28, 0 },  /* 90 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"0\":null}", 84, 0 },  /* 91 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 96, 0 },  /* 92 */
	{ "{\"body\":{\"message\":\"test message\"},\"type\":\"kdeconnect.ping\"}", 60, 0 },  /* 93 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 108, 0 },  /* 94 */
	{ "{\"body\":{\"message\":[null]},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 112, 0 },  /* 95 */
	{ "{\"body\":{\"message\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 92, 0 },  /* 96 */
	{ "{\"body\":{\"message\":[null]},\"id\":[null,null]}", 44, 0 },  /* 97 */
	{ "{\"body\":{\"message\":[]},\"type\":\"\"}", 33, 0 },  /* 98 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 124, 0 },  /* 99 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null]}", 89, 0 },  /* 100 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 155, 0 },  /* 101 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 125, 1 },  /* 102 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null}", 86, 0 },  /* 103 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"id\":[null],\"type\":[null]}", 58, 0 },  /* 104 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 92, 0 },  /* 105 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 138, 0 },  /* 106 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"id\":{},\"0\":null}", 53, 0 },  /* 107 */
	{ "{\"id\":{},\"type\":{}}", 19, 0 },  /* 108 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 139, 0 },  /* 109 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 89, 0 },  /* 110 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 66, 0 },  /* 111 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 73, 1 },  /* 112 */
	{ "{\"body\":{\"message\":{}},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 89, 0 },  /* 113 */
	{ "\"\"", 2, 0 },  /* 114 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"id\":{\"0\":null}}", 50, 0 },  /* 115 */
	{ "{\"body\":{\"message\":[]},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 81, 0 },  /* 116 */
	{ "{\"body\":{\"message\":[]},\"type\":\"\",\"0\":null}", 42, 0 },  /* 117 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.ping\"}", 105, 0 },  /* 118 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 105, 0 },  /* 119 */
	{ "{\"body\":null,\"type\":[],\"0\":null}", 32, 0 },  /* 120 */
	{ "{\"id\":[],\"type\":[],\"0\":null}", 28, 0 },  /* 121 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null],\"0\":null}", 93, 0 },  /* 122 */
	{ "{\"body\":{\"message\":[null,null]},\"type\":[]}", 42, 0 },  /* 123 */
	{ "{\"id\":0,\"type\":[]}", 18, 0 },  /* 124 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"id\":1}", 70, 0 },  /* 125 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null}", 68, 0 },  /* 126 */
	{ "{\"body\":{},\"id\":0}", 18, 0 },  /* 127 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 138, 0 },  /* 128 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"id\":null}", 82, 0 },  /* 129 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 144, 1 },  /* 130 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\"}", 116, 1 },  /* 131 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 68, 0 },  /* 132 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 116, 0 },  /* 133 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 154, 0 },  /* 134 */
	{ "{\"body\":null,\"id\":[]}", 21, 0 },  /* 135 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 84, 0 },  /* 136 */
	{ "{\"body\":{\"message\":{}},\"id\":[null],\"0\":null}", 44, 0 },  /* 137 */
	{ "{\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 42, 0 },  /* 138 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"id\":null}", 41, 0 },  /* 139 */
	{ "{\"body\":{\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 91, 1 },  /* 140 */
	{ "{\"body\":{\"message\":{}},\"id\":[null],\"type\":[null],\"0\":null}", 58, 0 },  /* 141 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 93, 0 },  /* 142 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 93, 0 },  /* 143 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"type\":{},\"0\":null}", 55, 0 },  /* 144 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"id\":[null],\"type\":[null],\"0\":null}", 67, 0 },  /* 145 */
	{ "{\"id\":0,\"type\":[],\"0\":null}", 27, 0 },  /* 146 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 91, 0 },  /* 147 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 98, 0 },  /* 148 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"id\":\"\",\"type\":\"\"}", 59, 0 },  /* 149 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"id\":{},\"0\":null}", 84, 0 },  /* 150 */
	{ "{\"body\":{\"message\":\"test message\"},\"id\":0,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 107, 1 },  /* 151 */
	{ "{\"body\":{\"message\":{}},\"id\":[null],\"type\":[null],\"0\":null,\"additionalProperties-test-unique\":null}", 98, 0 },  /* 152 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"id\":{}}", 44, 0 },  /* 153 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 99, 0 },  /* 154 */
	{ "{\"body\":\"\",\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 69, 0 },  /* 155 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"0\":null}", 101, 0 },  /* 156 */
	{ "{\"body\":{\"message\":null},\"id\":{}}", 33, 0 },  /* 157 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 83, 0 },  /* 158 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"type\":[null]}", 77, 0 },  /* 159 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"type\":[],\"0\":null}", 94, 0 },  /* 160 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"type\":[null],\"0\":null}", 55, 0 },  /* 161 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"type\":{\"0\":null}}", 52, 0 },  /* 162 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 125, 1 },  /* 163 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"0\":null}", 106, 0 },  /* 164 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 123, 0 },  /* 165 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"type\":null,\"0\":null}", 52, 0 },  /* 166 */
	{ "{\"body\":\"\",\"id\":[],\"type\":[],\"0\":null}", 38, 0 },  /* 167 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"id\":{}}", 75, 0 },  /* 168 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"type\":\"\"}", 42, 0 },  /* 169 */
	{ "{\"body\":{},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 52, 1 },  /* 170 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 84, 0 },  /* 171 */
	{ "{\"body\":{\"message\":\"\"},\"id\":1,\"type\":\"kdeconnect.ping\"}", 55, 1 },  /* 172 */
	{ "{\"body\":[null,null],\"id\":{\"0\":null}}", 36, 0 },  /* 173 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 108, 0 },  /* 174 */
	{ "{\"body\":{\"message\":[null]},\"type\":[null,null]}", 46, 0 },  /* 175 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 145, 0 },  /* 176 */
	{ "{\"body\":{\"message\":\"test message\"},\"id\":0,\"type\":\"kdeconnect.ping\"}", 67, 1 },  /* 177 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 156, 0 },  /* 178 */
	{ "{\"body\":{\"message\":{}},\"id\":[null],\"type\":[null]}", 49, 0 },  /* 179 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"type\":\"kdeconnect.ping\"}", 69, 0 },  /* 180 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"id\":null,\"type\":null,\"0\":null}", 62, 0 },  /* 181 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"id\":\"\",\"0\":null}", 49, 0 },  /* 182 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 148, 0 },  /* 183 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null}", 84, 0 },  /* 184 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 115, 0 },  /* 185 */
	{ "{\"body\":{\"message\":[null,null]},\"id\":[]}", 40, 0 },  /* 186 */
	{ "{\"body\":[null],\"id\":{},\"type\":{},\"0\":null}", 42, 0 },  /* 187 */
	{ "{\"id\":[null,null],\"type\":[null,null]}", 37, 0 },  /* 188 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 142, 0 },  /* 189 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\",\"0\":null}", 38, 0 },  /* 190 */
	{ "{\"body\":[null],\"id\":{}}", 23, 0 },  /* 191 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 88, 0 },  /* 192 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 103, 0 },  /* 193 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"id\":[null],\"0\":null}", 53, 0 },  /* 194 */
	{ "{\"body\":\"\",\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 78, 0 },  /* 195 */
	{ "{\"body\":{},\"type\":\"kdeconnect.ping\",\"0\":null}", 45, 0 },  /* 196 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"type\":\"\"}", 51, 0 },  /* 197 */
	{ "{\"body\":[null,null],\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 103, 0 },  /* 198 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"type\":[null],\"0\":null}", 86, 0 },  /* 199 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 93, 0 },  /* 200 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"id\":0,\"0\":null}", 48, 0 },  /* 201 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"type\":null}", 83, 0 },  /* 202 */
	{ "{\"body\":[null,null],\"type\":{\"0\":null},\"0\":null}", 47, 0 },  /* 203 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 135, 1 },  /* 204 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null]}", 82, 0 },  /* 205 */
	{ "{\"body\":[],\"id\":\"\"}", 19, 0 },  /* 206 */
	{ "{\"body\":[null],\"type\":{},\"0\":null}", 34, 0 },  /* 207 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\"}", 95, 1 },  /* 208 */
	{ "{\"body\":{\"0\":null},\"type\":\"kdeconnect.ping\"}", 44, 0 },  /* 209 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"type\":{}}", 46, 0 },  /* 210 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"0\":null}", 106, 0 },  /* 211 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 98, 0 },  /* 212 */
	{ "{\"body\":{\"message\":[null,null]},\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 213 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"type\":[]}", 90, 0 },  /* 214 */
	{ "{\"body\":{\"message\":[null]},\"id\":[null,null],\"type\":[null,null]}", 63, 0 },  /* 215 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 84, 0 },  /* 216 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[]}", 80, 0 },  /* 217 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\"}", 29, 0 },  /* 218 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 106, 0 },  /* 219 */
	{ "{\"body\":{\"message\":[]},\"id\":\"\"}", 31, 0 },  /* 220 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"id\":1}", 51, 0 },  /* 221 */
	{ "{\"body\":{\"message\":\"\"},\"id\":1,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 95, 1 },  /* 222 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null}}", 97, 0 },  /* 223 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 104, 1 },  /* 224 */
	{ "{\"id\":{},\"type\":{},\"0\":null}", 28, 0 },  /* 225 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 90, 0 },  /* 226 */
	{ "{\"body\":[null,null],\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 63, 0 },  /* 227 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 100, 1 },  /* 228 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1}", 91, 0 },  /* 229 */
	{ "{\"body\":\"\",\"id\":[],\"type\":[]}", 29, 0 },  /* 230 */
	{ "{\"body\":null,\"id\":[],\"0\":null}", 30, 0 },  /* 231 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 99, 0 },  /* 232 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"type\":{\"0\":null},\"0\":null}", 67, 0 },  /* 233 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 102, 0 },  /* 234 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"additionalProperties-test-unique\":null}", 141, 0 },  /* 235 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"type\":\"\",\"0\":null}", 51, 0 },  /* 236 */
	{ "{\"body\":{\"message\":\"\"},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 104, 1 },  /* 237 */
	{ "{\"body\":[null],\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 73, 0 },  /* 238 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 108, 0 },  /* 239 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"type\":\"kdeconnect.ping\"}", 57, 0 },  /* 240 */
	{ "{\"body\":{\"message\":\"test message\"},\"type\":\"kdeconnect.ping\",\"0\":null}", 69, 0 },  /* 241 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 90, 0 },  /* 242 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"id\":\"\",\"type\":\"\"}", 50, 0 },  /* 243 */
	{ "{\"body\":\"\",\"type\":[]}", 21, 0 },  /* 244 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"id\":null,\"0\":null}", 50, 0 },  /* 245 */
	{ "{\"body\":{\"message\":null},\"type\":{}}", 35, 0 },  /* 246 */
	{ "{\"id\":\"\",\"type\":\"\"}", 19, 0 },  /* 247 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 131, 1 },  /* 248 */
	{ "{\"body\":{\"message\":\"test message\"},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 76, 1 },  /* 249 */
	{ "{\"body\":{\"message\":{\"0\":null}},\"type\":null}", 43, 0 },  /* 250 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\"}", 107, 1 },  /* 251 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 97, 0 },  /* 252 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"type\":null}", 84, 0 },  /* 253 */
	{ "{\"body\":null,\"id\":[],\"type\":[]}", 31, 0 },  /* 254 */
	{ "{\"body\":\"\",\"id\":[]}", 19, 0 },  /* 255 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 134, 0 },  /* 256 */
	{ "{\"body\":[],\"type\":\"\",\"0\":null}", 30, 0 },  /* 257 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 91, 0 },  /* 258 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 110, 0 },  /* 259 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 102, 0 },  /* 260 */
	{ "{\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null}", 44, 0 },  /* 261 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"additionalProperties-test-unique\":null}", 129, 0 },  /* 262 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0}", 66, 0 },  /* 263 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1}", 79, 0 },  /* 264 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"id\":{\"0\":null},\"0\":null}", 59, 0 },  /* 265 */
	{ "{\"body\":[],\"type\":\"\"}", 21, 0 },  /* 266 */
	{ "{\"body\":null,\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 71, 0 },  /* 267 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 113, 1 },  /* 268 */
	{ "{\"body\":{\"message\":[null]},\"type\":[null,null],\"0\":null}", 55, 0 },  /* 269 */
	{ "{\"body\":{\"message\":{},\"0\":null},\"type\":[null]}", 46, 0 },  /* 270 */
	{ "{\"body\":{\"message\":\"\"},\"type\":\"kdeconnect.ping\"}", 48, 0 },  /* 271 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null]}", 89, 0 },  /* 272 */
	{ "{\"body\":{\"message\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null]}", 101, 0 },  /* 273 */
	{ "{\"id\":[],\"type\":\"kdeconnect.ping\",\"0\":null}", 43, 0 },  /* 274 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 157, 0 },  /* 275 */
	{ "{\"body\":{\"message\":null,\"0\":null},\"type\":{\"0\":null},\"0\":null}", 61, 0 },  /* 276 */
	{ "{\"body\":{\"message\":null},\"id\":{},\"0\":null}", 42, 0 },  /* 277 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[],\"0\":null}", 89, 0 },  /* 278 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"additionalProperties-test-unique\":null}", 131, 1 },  /* 279 */
	{ "{\"body\":{\"message\":null},\"id\":{},\"type\":{},\"0\":null}", 52, 0 },  /* 280 */
	{ "{\"body\":{\"message\":[],\"additionalProperties-test-unique\":null},\"id\":[null]}", 75, 0 },  /* 281 */
	{ "{\"body\":{\"message\":{},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null}", 117, 0 },  /* 282 */
	{ "{\"id\":[],\"type\":[]}", 19, 0 },  /* 283 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 79, 0 },  /* 284 */
	{ "{\"body\":{\"message\":{}},\"id\":[null]}", 35, 0 },  /* 285 */
	{ "{\"body\":{\"message\":\"\"},\"id\":1}", 30, 0 },  /* 286 */
	{ "{\"body\":{\"message\":\"test message\"},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 116, 1 },  /* 287 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[null,null],\"type\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null}", 165, 0 },  /* 288 */
	{ "{\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 42, 0 },  /* 289 */
	{ "{\"body\":{\"message\":\"test message\"},\"id\":0}", 42, 0 },  /* 290 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 93, 0 },  /* 291 */
	{ "{\"id\":[null],\"type\":[null]}", 27, 0 },  /* 292 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"id\":{\"0\":null},\"0\":null}", 65, 0 },  /* 293 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"type\":{},\"0\":null}", 86, 0 },  /* 294 */
	{ "{\"id\":[],\"type\":\"kdeconnect.ping\"}", 34, 0 },  /* 295 */
	{ "{\"id\":null,\"type\":null}", 23, 0 },  /* 296 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"type\":\"\",\"0\":null}", 60, 0 },  /* 297 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"additionalProperties-test-unique\":null}", 132, 0 },  /* 298 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 109, 0 },  /* 299 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"additionalProperties-test-unique\":null}", 155, 0 },  /* 300 */
	{ "{\"body\":{\"message\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 83, 0 },  /* 301 */
	{ "{\"body\":{\"message\":[null,null]},\"id\":[],\"0\":null}", 49, 0 },  /* 302 */
	{ "{}", 2, 0 },  /* 303 */
	{ "{\"body\":[null,null],\"id\":{\"0\":null},\"0\":null}", 45, 0 },  /* 304 */
	{ "{\"body\":{\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 100, 1 },  /* 305 */
	{ "{\"body\":{\"0\":null},\"id\":1,\"0\":null}", 35, 0 },  /* 306 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"type\":null}", 86, 0 },  /* 307 */
	{ "{\"body\":null,\"id\":[],\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 80, 0 },  /* 308 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"additionalProperties-test-unique\":null}", 125, 0 },  /* 309 */
	{ "{\"body\":{\"message\":[null,null]},\"id\":[],\"type\":[],\"additionalProperties-test-unique\":null}", 90, 0 },  /* 310 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"id\":1,\"0\":null}", 60, 0 },  /* 311 */
	{ "{\"body\":{\"message\":{}},\"type\":[null],\"0\":null}", 46, 0 },  /* 312 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 99, 0 },  /* 313 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\"}", 104, 1 },  /* 314 */
	{ "{\"body\":{\"message\":{}},\"type\":[null]}", 37, 0 },  /* 315 */
	{ "{\"body\":[null],\"type\":{}}", 25, 0 },  /* 316 */
	{ "{\"id\":{\"0\":null},\"type\":{\"0\":null}}", 35, 0 },  /* 317 */
	{ "[null,null]", 11, 0 },  /* 318 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"id\":{\"0\":null}}", 56, 0 },  /* 319 */
	{ "{\"id\":1,\"type\":\"kdeconnect.ping\"}", 33, 0 },  /* 320 */
	{ "null", 4, 0 },  /* 321 */
	{ "{\"body\":{\"message\":[],\"0\":null},\"id\":\"\"}", 40, 0 },  /* 322 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"type\":{\"0\":null},\"0\":null}", 108, 0 },  /* 323 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 134, 0 },  /* 324 */
	{ "{\"body\":{\"message\":[],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":[]}", 80, 0 },  /* 325 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"type\":{}}", 77, 0 },  /* 326 */
	{ "{\"body\":{},\"id\":0,\"type\":\"kdeconnect.ping\"}", 43, 1 },  /* 327 */
	{ "{\"id\":[null],\"type\":[null],\"0\":null}", 36, 0 },  /* 328 */
	{ "[null]", 6, 0 },  /* 329 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 74, 0 },  /* 330 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 88, 0 },  /* 331 */
	{ "{\"body\":{\"message\":\"\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 97, 0 },  /* 332 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"type\":null,\"0\":null}", 93, 0 },  /* 333 */
	{ "{\"body\":{\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 60, 1 },  /* 334 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null}}", 115, 0 },  /* 335 */
	{ "{\"body\":[],\"id\":\"\",\"0\":null}", 28, 0 },  /* 336 */
	{ "{\"body\":{\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 91, 1 },  /* 337 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":\"kdeconnect.ping\",\"0\":null}", 116, 1 },  /* 338 */
	{ "{\"body\":{\"message\":{},\"additionalProperties-test-unique\":null},\"id\":[null],\"type\":[null],\"0\":null}", 98, 0 },  /* 339 */
	{ "{\"body\":{\"message\":\"\",\"0\":null},\"id\":0,\"type\":\"kdeconnect.ping\"}", 64, 1 },  /* 340 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"0\":null}", 100, 0 },  /* 341 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null}", 85, 1 },  /* 342 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 136, 0 },  /* 343 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{}}", 85, 0 },  /* 344 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null,\"additionalProperties-test-unique\":null}", 143, 0 },  /* 345 */
	{ "{\"body\":{\"message\":[]},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 90, 0 },  /* 346 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 91, 0 },  /* 347 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":{\"0\":null},\"type\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null}", 164, 0 },  /* 348 */
	{ "{\"body\":{\"message\":[null],\"additionalProperties-test-unique\":null},\"id\":{},\"type\":{},\"0\":null}", 94, 0 },  /* 349 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\",\"additionalProperties-test-unique\":null}", 69, 0 },  /* 350 */
	{ "{\"body\":{\"message\":\"\",\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\",\"0\":null,\"additionalProperties-test-unique\":null}", 144, 1 },  /* 351 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null},\"type\":\"kdeconnect.ping\",\"0\":null}", 78, 0 },  /* 352 */
	{ "{\"body\":{\"message\":\"\"},\"type\":\"kdeconnect.ping\",\"0\":null}", 57, 0 },  /* 353 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 94, 0 },  /* 354 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 107, 0 },  /* 355 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"id\":0,\"type\":[],\"0\":null,\"additionalProperties-test-unique\":null}", 141, 0 },  /* 356 */
	{ "{\"body\":[null,null],\"type\":{\"0\":null}}", 38, 0 },  /* 357 */
	{ "{\"body\":{\"message\":[null]},\"id\":[null,null],\"0\":null}", 53, 0 },  /* 358 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null}", 98, 0 },  /* 359 */
	{ "{\"body\":[null],\"id\":{},\"type\":{},\"0\":null,\"additionalProperties-test-unique\":null}", 82, 0 },  /* 360 */
	{ "{\"body\":{\"0\":null},\"id\":1}", 26, 0 },  /* 361 */
	{ "{\"body\":{\"message\":[null],\"0\":null},\"id\":{},\"type\":{},\"0\":null}", 63, 0 },  /* 362 */
	{ "{\"body\":{\"0\":null,\"additionalProperties-test-unique\":null},\"id\":0,\"0\":null}", 75, 0 },  /* 363 */
	{ "{\"body\":{\"message\":{\"0\":null},\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"additionalProperties-test-unique\":null}", 133, 0 },  /* 364 */
	{ "{\"body\":[],\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 78, 0 },  /* 365 */
	{ "{\"body\":{\"message\":\"test message\",\"additionalProperties-test-unique\":null},\"type\":[]}", 85, 0 },  /* 366 */
	{ "{\"body\":{\"message\":null},\"id\":{},\"type\":{}}", 43, 0 },  /* 367 */
	{ "{\"body\":{\"message\":{\"0\":null},\"0\":null,\"additionalProperties-test-unique\":null},\"type\":[null,null]}", 99, 0 },  /* 368 */
	{ "{\"body\":{\"message\":[null,null],\"additionalProperties-test-unique\":null},\"id\":null,\"type\":null,\"0\":null}", 103, 0 },  /* 369 */
	{ "{\"body\":{\"message\":null,\"0\":null,\"additionalProperties-test-unique\":null},\"id\":1,\"type\":\"kdeconnect.ping\"}", 106, 0 },  /* 370 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"id\":\"\",\"0\":null}", 58, 0 },  /* 371 */
	{ "{\"body\":{\"message\":[null,null],\"0\":null},\"id\":\"\",\"type\":\"\",\"0\":null,\"additionalProperties-test-unique\":null}", 108, 0 },  /* 372 */
	{ "{\"body\":{\"message\":\"test message\",\"0\":null,\"additionalProperties-test-unique\":null},\"type\":\"kdeconnect.ping\"}", 109, 0 },  /* 373 */
	{ "{\"body\":{\"message\":[null],\"0\":null,\"additionalProperties-test-unique\":null},\"id\":null,\"0\":null}", 95, 0 },  /* 374 */
	{ "{\"id\":[null,null],\"type\":[null,null],\"0\":null}", 46, 0 },  /* 375 */
	{ "\342\230\240", 3, 0 },  /* 376 */
};
