name: CD

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  report:
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name}}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        env:
          CX_SETUP_COVERAGE: true
          CX_SETUP_OPTIONS: '-Ddocumentation=true -Dtests=true'
          CX_LCOV_INCLUDE_PATH: '${{ github.workspace }}/src/*'
          CX_LCOV_EXCLUDE_PATH: '*/tests/* */subprojects/*'
        run: |
          ./tests/extra/ci-runner.sh test

      - name: Report
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/_build/meson-logs/coverage.info

      - name: Coverage
        continue-on-error: true
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: _build/meson-logs/coverage-html
          target-folder: coverage
          single-commit: true

      - name: Documentation
        continue-on-error: true
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: _build/doc/sdk/valent
          target-folder: documentation
          single-commit: true

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatpak-github-actions:gnome-43
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare Docker
        if: ${{ matrix.arch == 'aarch64' }}
        run: |
          dnf -y install docker

      - name: Prepare QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build
        uses: andyholmes/flatpak-github-actions/flatpak-builder@valent
        with:
          arch: ${{ matrix.arch }}
          bundle: ca.andyholmes.Valent.flatpak
          manifest-path: build-aux/flatpak/ca.andyholmes.Valent.json
