name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  report:
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.ref_name}}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Test
        id: test
        uses: andyholmes/actuary@main
        with:
          suite: test
          setup-args: |
            -Ddocumentation=true
            -Dtests=true
          test-coverage: true
          lcov-include: '${{ github.workspace }}/src/*'

      - name: Coverage Report
        continue-on-error: true
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: ${{ steps.test.outputs.coverage-html }}
          target-folder: coverage
          single-commit: true

      - name: Documentation
        continue-on-error: true
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: _build/doc/sdk/valent
          target-folder: documentation
          single-commit: true

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:46
      options: --privileged
    permissions:
      contents: write

    strategy:
      max-parallel: 1
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        id: build
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/flatpak/ca.andyholmes.Valent.json
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: ${{ steps.build.outputs.repository }}
          target-folder: repo
          single-commit: true
