name: Static Analysis

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.c'
      - '**/*.h'

jobs:
  codeql:
    name: Static Analysis (CodeQL)
    runs-on: ubuntu-latest

    steps:
        - run: echo "No analysis required"

  llvm:
    name: Static Analysis (LLVM)
    runs-on: ubuntu-latest

    steps:
        - run: echo "No analysis required"
